/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CSCPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var CSCSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.testButton = null;
    this.testStatus = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u4E2D\u6587\u9519\u522B\u5B57\u68C0\u6D4B\u8BBE\u7F6E" });
    this.renderApiSettings(containerEl);
    this.renderEngineSettings(containerEl);
    this.renderIgnoredWordsSettings(containerEl);
    this.renderAdvancedSettings(containerEl);
  }
  renderApiSettings(containerEl) {
    containerEl.createEl("h3", { text: "API \u914D\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u8F93\u5165\u4F60\u7684 AI \u670D\u52A1 API Key\uFF08\u652F\u6301 DeepSeek\u3001OpenAI \u517C\u5BB9\u63A5\u53E3\uFF09").addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API \u7AEF\u70B9").setDesc("AI \u670D\u52A1\u7684 API \u7AEF\u70B9\u5730\u5740").addText(
      (text) => text.setPlaceholder("https://api.deepseek.com/v1/chat/completions").setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
        this.plugin.settings.apiEndpoint = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B\u540D\u79F0").setDesc("\u4F7F\u7528\u7684\u6A21\u578B\u540D\u79F0").addText(
      (text) => text.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.modelName).onChange(async (value) => {
        this.plugin.settings.modelName = value;
        await this.plugin.saveSettings();
      })
    );
    const testSetting = new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u6D4B\u8BD5 API \u914D\u7F6E\u662F\u5426\u6B63\u786E");
    this.testStatus = testSetting.controlEl.createDiv({ cls: "csc-test-status" });
    testSetting.addButton((btn) => {
      btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
      btn.setClass("csc-test-btn");
      btn.onClick(async () => {
        await this.testConnection(btn);
      });
      this.testButton = btn.buttonEl;
    });
  }
  async testConnection(btn) {
    var _a;
    const { apiKey, apiEndpoint, modelName, timeout } = this.plugin.settings;
    if (!apiKey) {
      this.updateTestStatus("error", "\u8BF7\u5148\u8F93\u5165 API Key");
      return;
    }
    if (!apiEndpoint) {
      this.updateTestStatus("error", "\u8BF7\u5148\u8F93\u5165 API \u7AEF\u70B9");
      return;
    }
    btn.setDisabled(true);
    btn.setButtonText("\u6D4B\u8BD5\u4E2D...");
    this.updateTestStatus("testing", "\u6B63\u5728\u6D4B\u8BD5\u8FDE\u63A5...");
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeout);
    try {
      const response = await fetch(apiEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: modelName,
          messages: [
            {
              role: "user",
              content: "\u4F60\u597D"
            }
          ],
          max_tokens: 10
        }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      if (!response.ok) {
        const errorText = await response.text();
        let errorMsg = `HTTP ${response.status}`;
        try {
          const errorJson = JSON.parse(errorText);
          if ((_a = errorJson.error) == null ? void 0 : _a.message) {
            errorMsg = errorJson.error.message;
          }
        } catch (e) {
        }
        this.updateTestStatus("error", `\u8FDE\u63A5\u5931\u8D25: ${errorMsg}`);
        return;
      }
      const data = await response.json();
      if (data.choices && data.choices.length > 0) {
        this.updateTestStatus("success", "\u8FDE\u63A5\u6210\u529F\uFF01API \u914D\u7F6E\u6B63\u786E");
        new import_obsidian.Notice("API \u8FDE\u63A5\u6D4B\u8BD5\u6210\u529F");
      } else {
        this.updateTestStatus("error", "\u54CD\u5E94\u683C\u5F0F\u5F02\u5E38\uFF0C\u8BF7\u68C0\u67E5\u6A21\u578B\u540D\u79F0");
      }
    } catch (error) {
      clearTimeout(timeoutId);
      if (error instanceof Error) {
        if (error.name === "AbortError") {
          this.updateTestStatus("error", "\u8FDE\u63A5\u8D85\u65F6\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u6216\u589E\u52A0\u8D85\u65F6\u65F6\u95F4");
        } else {
          this.updateTestStatus("error", `\u8FDE\u63A5\u5931\u8D25: ${error.message}`);
        }
      } else {
        this.updateTestStatus("error", "\u8FDE\u63A5\u5931\u8D25: \u672A\u77E5\u9519\u8BEF");
      }
    } finally {
      btn.setDisabled(false);
      btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
    }
  }
  updateTestStatus(status, message) {
    if (!this.testStatus)
      return;
    this.testStatus.empty();
    this.testStatus.className = "csc-test-status";
    const statusEl = this.testStatus.createSpan({
      cls: `csc-test-status-${status}`,
      text: message
    });
  }
  renderEngineSettings(containerEl) {
    containerEl.createEl("h3", { text: "\u5F15\u64CE\u914D\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528 AI \u5F15\u64CE").setDesc("\u4F7F\u7528 AI \u8FDB\u884C\u8BED\u5883\u76F8\u5173\u7684\u9519\u522B\u5B57\u68C0\u6D4B\uFF08\u9700\u8981 API Key\uFF09").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.aiEngineEnabled).onChange(async (value) => {
        this.plugin.settings.aiEngineEnabled = value;
        await this.plugin.saveSettings();
      })
    );
  }
  renderIgnoredWordsSettings(containerEl) {
    containerEl.createEl("h3", { text: "\u5FFD\u7565\u8BCD\u5E93" });
    new import_obsidian.Setting(containerEl).setName("\u5FFD\u7565\u8BCD\u5217\u8868").setDesc("\u8FD9\u4E9B\u8BCD\u5C06\u4E0D\u4F1A\u88AB\u68C0\u6D4B\u4E3A\u9519\u522B\u5B57\uFF08\u6BCF\u884C\u4E00\u4E2A\u8BCD\uFF09").addTextArea(
      (text) => text.setPlaceholder("\u8F93\u5165\u8981\u5FFD\u7565\u7684\u8BCD\u6C47...").setValue(this.plugin.settings.ignoredWords.join("\n")).onChange(async (value) => {
        this.plugin.settings.ignoredWords = value.split("\n").map((word) => word.trim()).filter((word) => word.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
  renderAdvancedSettings(containerEl) {
    containerEl.createEl("h3", { text: "\u9AD8\u7EA7\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u5206\u6BB5\u957F\u5EA6").setDesc("AI \u68C0\u6D4B\u65F6\u6BCF\u6BB5\u6587\u672C\u7684\u6700\u5927\u5B57\u7B26\u6570\uFF08\u5EFA\u8BAE 1000-2000\uFF09").addSlider(
      (slider) => slider.setLimits(500, 3e3, 100).setValue(this.plugin.settings.maxSegmentLength).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxSegmentLength = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8BF7\u6C42\u8D85\u65F6").setDesc("API \u8BF7\u6C42\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09").addText(
      (text) => text.setValue(String(this.plugin.settings.timeout)).onChange(async (value) => {
        const timeout = parseInt(value, 10);
        if (!isNaN(timeout) && timeout > 0) {
          this.plugin.settings.timeout = timeout;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_CSC = "csc-view";
var CSCView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.results = [];
    this.status = "idle";
    this.errorMessage = "";
    this.containerDiv = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CSC;
  }
  getDisplayText() {
    return "\u9519\u522B\u5B57\u68C0\u6D4B";
  }
  getIcon() {
    return "spell-check";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setResults(results) {
    this.results = results;
    this.render();
  }
  setStatus(status, errorMessage) {
    this.status = status;
    this.errorMessage = errorMessage || "";
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.createEl("div", { cls: "csc-container" }, (div) => {
      this.containerDiv = div;
      this.renderHeader(div);
      this.renderContent(div);
      this.renderFooter(div);
    });
  }
  renderHeader(container) {
    container.createEl("div", { cls: "csc-header" }, (header) => {
      header.createEl("div", { cls: "csc-header-top" }, (top) => {
        top.createEl("div", { cls: "csc-title-row" }, (titleRow) => {
          const iconEl = titleRow.createEl("div", { cls: "csc-title-icon" });
          (0, import_obsidian2.setIcon)(iconEl, "spell-check");
          titleRow.createEl("h3", { text: "\u9519\u522B\u5B57\u68C0\u6D4B", cls: "csc-title" });
        });
        const statusEl = top.createEl("div", { cls: "csc-status" });
        this.renderStatus(statusEl);
      });
      header.createEl("button", {
        cls: "csc-detect-btn"
      }, (btn) => {
        if (this.status === "detecting") {
          btn.createEl("div", { cls: "csc-btn-spinner" });
          btn.createEl("span", { text: "\u68C0\u6D4B\u4E2D..." });
          btn.disabled = true;
        } else {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "search");
          btn.createEl("span", { text: "\u5F00\u59CB\u68C0\u6D4B" });
        }
        btn.addEventListener("click", () => {
          this.startDetection();
        });
      });
    });
  }
  renderStatus(container) {
    switch (this.status) {
      case "idle":
        container.createEl("span", {
          text: "\u51C6\u5907\u5C31\u7EEA",
          cls: "csc-status-badge csc-status-idle"
        });
        break;
      case "detecting":
        container.createEl("span", {
          text: "\u68C0\u6D4B\u4E2D",
          cls: "csc-status-badge csc-status-detecting"
        });
        break;
      case "completed":
        const count = this.results.length;
        if (count === 0) {
          container.createEl("span", {
            text: "\u672A\u53D1\u73B0\u95EE\u9898",
            cls: "csc-status-badge csc-status-success"
          });
        } else {
          container.createEl("span", {
            text: `\u53D1\u73B0 ${count} \u5904\u95EE\u9898`,
            cls: "csc-status-badge csc-status-warning"
          });
        }
        break;
      case "error":
        container.createEl("span", {
          text: "\u68C0\u6D4B\u5931\u8D25",
          cls: "csc-status-badge csc-status-error"
        });
        break;
    }
  }
  renderContent(container) {
    container.createEl("div", { cls: "csc-content" }, (content) => {
      if (this.status === "detecting") {
        this.renderLoading(content);
        return;
      }
      if (this.status === "error") {
        this.renderError(content);
        return;
      }
      if (this.results.length === 0 && this.status === "completed") {
        this.renderSuccess(content);
        return;
      }
      if (this.results.length === 0) {
        this.renderEmpty(content);
        return;
      }
      this.renderResults(content);
    });
  }
  renderLoading(container) {
    container.createEl("div", { cls: "csc-loading" }, (loading) => {
      loading.createEl("div", { cls: "csc-loading-animation" }, (anim) => {
        for (let i = 0; i < 3; i++) {
          anim.createEl("div", { cls: "csc-loading-dot" });
        }
      });
      loading.createEl("div", { cls: "csc-loading-text" }, (text) => {
        text.createEl("span", { text: "AI \u6B63\u5728\u5206\u6790\u6587\u672C..." });
        text.createEl("span", { text: "\u8BF7\u7A0D\u5019", cls: "csc-loading-sub" });
      });
    });
  }
  renderError(container) {
    container.createEl("div", { cls: "csc-message csc-message-error" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "alert-circle");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "\u68C0\u6D4B\u5931\u8D25", cls: "csc-message-title" });
        content.createEl("div", { text: this.errorMessage || "\u8BF7\u68C0\u67E5 API \u914D\u7F6E\u540E\u91CD\u8BD5", cls: "csc-message-desc" });
      });
    });
  }
  renderSuccess(container) {
    container.createEl("div", { cls: "csc-message csc-message-success" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "check-circle");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "\u592A\u68D2\u4E86\uFF01", cls: "csc-message-title" });
        content.createEl("div", { text: "\u6CA1\u6709\u53D1\u73B0\u9519\u522B\u5B57", cls: "csc-message-desc" });
      });
    });
  }
  renderEmpty(container) {
    container.createEl("div", { cls: "csc-message csc-message-empty" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "file-text");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "\u51C6\u5907\u68C0\u6D4B", cls: "csc-message-title" });
        content.createEl("div", { text: "\u70B9\u51FB\u4E0A\u65B9\u6309\u94AE\u5F00\u59CB\u68C0\u6D4B\u5F53\u524D\u6587\u6863", cls: "csc-message-desc" });
      });
    });
  }
  renderResults(container) {
    container.createEl("div", { cls: "csc-result-list" }, (list) => {
      this.results.forEach((result, index) => {
        this.renderResultCard(list, result, index);
      });
    });
  }
  renderResultCard(container, result, index) {
    container.createEl("div", { cls: "csc-result-card" }, (card) => {
      card.createEl("div", { cls: "csc-card-header" }, (header) => {
        header.createEl("div", { cls: "csc-card-index" }, (indexEl) => {
          indexEl.createEl("span", { text: String(index + 1) });
        });
        header.createEl("div", { cls: "csc-card-source" }, (source) => {
          source.createEl("span", { text: "AI \u68C0\u6D4B" });
        });
      });
      card.createEl("div", { cls: "csc-card-error" }, (error) => {
        error.createEl("div", { cls: "csc-error-row" }, (row) => {
          row.createEl("span", { text: "\u539F\u6587\uFF1A", cls: "csc-error-label" });
          row.createEl("span", { text: result.original, cls: "csc-error-text" });
        });
        error.createEl("div", { cls: "csc-arrow" }, (arrow) => {
          (0, import_obsidian2.setIcon)(arrow, "arrow-down");
        });
        error.createEl("div", { cls: "csc-correct-row" }, (row) => {
          row.createEl("span", { text: "\u5EFA\u8BAE\uFF1A", cls: "csc-correct-label" });
          row.createEl("span", { text: result.suggestions[0], cls: "csc-correct-text" });
        });
      });
      if (result.reason) {
        card.createEl("div", { cls: "csc-card-reason" }, (reason) => {
          const iconEl = reason.createEl("div", { cls: "csc-reason-icon" });
          (0, import_obsidian2.setIcon)(iconEl, "info");
          reason.createEl("span", { text: result.reason });
        });
      }
      card.createEl("div", { cls: "csc-card-actions" }, (actions) => {
        result.suggestions.forEach((suggestion) => {
          actions.createEl("button", {
            text: `\u66FF\u6362\u4E3A\u300C${suggestion}\u300D`,
            cls: "csc-action-btn csc-action-apply"
          }, (btn) => {
            btn.addEventListener("click", () => {
              this.applyFix(result.offset, result.original, suggestion, index);
            });
          });
        });
        actions.createEl("button", {
          cls: "csc-action-btn csc-action-ignore"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon-small" }), "x");
          btn.createEl("span", { text: "\u5FFD\u7565" });
          btn.addEventListener("click", () => {
            this.ignoreWord(result.original, index);
          });
        });
      });
    });
  }
  renderFooter(container) {
    if (this.results.length === 0)
      return;
    container.createEl("div", { cls: "csc-footer" }, (footer) => {
      footer.createEl("button", {
        cls: "csc-footer-btn csc-footer-apply"
      }, (btn) => {
        (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "check");
        btn.createEl("span", { text: "\u5168\u90E8\u66FF\u6362" });
        btn.addEventListener("click", () => {
          this.applyAllFixes();
        });
      });
      footer.createEl("button", {
        cls: "csc-footer-btn csc-footer-ignore"
      }, (btn) => {
        (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "x-circle");
        btn.createEl("span", { text: "\u5168\u90E8\u5FFD\u7565" });
        btn.addEventListener("click", () => {
          this.ignoreAllWords();
        });
      });
    });
  }
  startDetection() {
    this.plugin.startDetection();
  }
  applyFix(offset, original, replacement, index) {
    const success = this.plugin.applyFix(offset, original, replacement);
    if (success) {
      this.results = this.plugin.getResults();
      this.render();
    }
  }
  ignoreWord(word, index) {
    if (!this.plugin.settings.ignoredWords.includes(word)) {
      this.plugin.settings.ignoredWords.push(word);
      this.plugin.saveSettings();
    }
    this.results.splice(index, 1);
    this.render();
  }
  applyAllFixes() {
    this.plugin.applyAllFixes();
    this.results = [];
    this.render();
  }
  ignoreAllWords() {
    this.results.forEach((result) => {
      if (!this.plugin.settings.ignoredWords.includes(result.original)) {
        this.plugin.settings.ignoredWords.push(result.original);
      }
    });
    this.plugin.saveSettings();
    this.results = [];
    this.render();
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
  modelName: "deepseek-chat",
  aiEngineEnabled: true,
  ignoredWords: [],
  maxSegmentLength: 1500,
  timeout: 3e4
};

// src/detector/scheduler.ts
var import_obsidian4 = require("obsidian");

// src/text/extractor.ts
var import_obsidian3 = require("obsidian");
var TextExtractor = class {
  constructor(app) {
    this.app = app;
  }
  extractText() {
    const mdView = this.getMarkdownView();
    if (!mdView) {
      return null;
    }
    const editor = mdView.editor;
    if (!editor) {
      return null;
    }
    const selection = editor.getSelection();
    if (selection && selection.length > 0) {
      const from = editor.posToOffset(editor.getCursor("from"));
      const to = editor.posToOffset(editor.getCursor("to"));
      return {
        text: selection,
        hasSelection: true,
        selectionRange: { from, to }
      };
    }
    return {
      text: editor.getValue(),
      hasSelection: false
    };
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (activeView) {
      return activeView;
    }
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView && view.getMode() === "source") {
        return view;
      }
    }
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView) {
        return view;
      }
    }
    return null;
  }
};

// src/text/cleaner.ts
var TextCleaner = class {
  clean(originalText) {
    let text = originalText;
    const mappings = [];
    let cleanOffset = 0;
    let originalOffset = 0;
    const processedText = this.processText(text, originalOffset, cleanOffset, mappings);
    return {
      text: processedText.text,
      mappings: processedText.mappings
    };
  }
  processText(text, startOriginalOffset, startCleanOffset, mappings) {
    let result = "";
    let cleanOffset = startCleanOffset;
    let originalOffset = startOriginalOffset;
    let i = 0;
    while (i < text.length) {
      const yamlResult = this.tryExtractYamlFrontMatter(text, i);
      if (yamlResult) {
        for (let j = 0; j < yamlResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += yamlResult.length;
        i += yamlResult.length;
        continue;
      }
      const codeBlockResult = this.tryExtractCodeBlock(text, i);
      if (codeBlockResult) {
        for (let j = 0; j < codeBlockResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += codeBlockResult.length;
        i += codeBlockResult.length;
        continue;
      }
      const inlineCodeResult = this.tryExtractInlineCode(text, i);
      if (inlineCodeResult) {
        for (let j = 0; j < inlineCodeResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += inlineCodeResult.length;
        i += inlineCodeResult.length;
        continue;
      }
      const htmlResult = this.tryExtractHtmlTag(text, i);
      if (htmlResult) {
        for (let j = 0; j < htmlResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += htmlResult.length;
        i += htmlResult.length;
        continue;
      }
      const linkResult = this.tryExtractLink(text, i);
      if (linkResult) {
        const displayText = linkResult.displayText;
        for (let j = 0; j < linkResult.urlPart.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += linkResult.urlPart.length;
        i += linkResult.urlPart.length;
        for (let j = 0; j < displayText.length; j++) {
          mappings.push({
            cleanOffset: cleanOffset + j,
            originalOffset: originalOffset + j
          });
        }
        result += displayText;
        cleanOffset += displayText.length;
        originalOffset += displayText.length;
        i += displayText.length;
        continue;
      }
      mappings.push({
        cleanOffset,
        originalOffset
      });
      result += text[i];
      cleanOffset++;
      originalOffset++;
      i++;
    }
    return { text: result, mappings };
  }
  tryExtractYamlFrontMatter(text, start) {
    if (start !== 0)
      return null;
    if (!text.startsWith("---", start))
      return null;
    const endIndex = text.indexOf("---", 3);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 3);
  }
  tryExtractCodeBlock(text, start) {
    if (!text.startsWith("```", start))
      return null;
    const endIndex = text.indexOf("```", start + 3);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 3);
  }
  tryExtractInlineCode(text, start) {
    if (text[start] !== "`")
      return null;
    if (text.startsWith("```", start))
      return null;
    const endIndex = text.indexOf("`", start + 1);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 1);
  }
  tryExtractHtmlTag(text, start) {
    if (text[start] !== "<")
      return null;
    const endIndex = text.indexOf(">", start);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 1);
  }
  tryExtractLink(text, start) {
    const linkRegex = /^\[([^\]]*)\]\(([^)]+)\)/;
    const match = text.substring(start).match(linkRegex);
    if (!match)
      return null;
    const fullMatch = match[0];
    const displayText = match[1];
    const urlPart = fullMatch.substring(fullMatch.indexOf("]("));
    return {
      urlPart: `](${match[2]})`,
      displayText
    };
  }
};

// src/text/mapper.ts
var OffsetMapper = class {
  constructor(mappings) {
    this.mappings = mappings;
  }
  cleanOffsetToOriginal(cleanOffset) {
    for (let i = 0; i < this.mappings.length; i++) {
      if (this.mappings[i].cleanOffset === cleanOffset) {
        return this.mappings[i].originalOffset;
      }
    }
    for (let i = this.mappings.length - 1; i >= 0; i--) {
      if (this.mappings[i].cleanOffset !== -1 && this.mappings[i].cleanOffset < cleanOffset) {
        const diff = cleanOffset - this.mappings[i].cleanOffset;
        return this.mappings[i].originalOffset + diff;
      }
    }
    return cleanOffset;
  }
  originalOffsetToClean(originalOffset) {
    for (let i = 0; i < this.mappings.length; i++) {
      if (this.mappings[i].originalOffset === originalOffset) {
        return this.mappings[i].cleanOffset;
      }
    }
    for (let i = this.mappings.length - 1; i >= 0; i--) {
      if (this.mappings[i].originalOffset < originalOffset) {
        const diff = originalOffset - this.mappings[i].originalOffset;
        const targetClean = this.mappings[i].cleanOffset + diff;
        if (targetClean >= 0) {
          return targetClean;
        }
      }
    }
    return originalOffset;
  }
  isValidCleanOffset(offset) {
    return offset >= 0 && offset < this.mappings.length;
  }
  isValidOriginalOffset(offset) {
    var _a;
    return this.mappings.some((m) => m.originalOffset === offset) || offset >= 0 && offset <= ((_a = this.mappings[this.mappings.length - 1]) == null ? void 0 : _a.originalOffset);
  }
};

// src/text/segmenter.ts
var TextSegmenter = class {
  constructor(maxSegmentLength = 1500) {
    this.maxSegmentLength = maxSegmentLength;
  }
  segment(text) {
    const paragraphs = this.splitByParagraphs(text);
    const segments = [];
    let currentSegment = "";
    let currentStartOffset = 0;
    let currentOffset = 0;
    for (const paragraph of paragraphs) {
      if (currentSegment.length + paragraph.length + 1 > this.maxSegmentLength) {
        if (currentSegment.length > 0) {
          const trimmed = currentSegment.trimStart();
          const trimOffset = currentSegment.length - trimmed.length;
          const finalText = trimmed.trimEnd();
          if (finalText.length > 0) {
            segments.push({
              text: finalText,
              startOffset: currentStartOffset + trimOffset,
              endOffset: currentOffset - (trimmed.length - finalText.length)
            });
          }
          currentSegment = "";
          currentStartOffset = currentOffset;
        }
        if (paragraph.length > this.maxSegmentLength) {
          const subSegments = this.splitLongParagraph(paragraph, currentStartOffset);
          segments.push(...subSegments);
          currentStartOffset = currentOffset + paragraph.length;
          currentOffset = currentStartOffset;
          continue;
        }
      }
      if (currentSegment.length > 0) {
        currentSegment += "\n";
        currentOffset++;
      }
      if (currentSegment.length === 0) {
        currentStartOffset = currentOffset;
      }
      currentSegment += paragraph;
      currentOffset += paragraph.length;
    }
    if (currentSegment.trim().length > 0) {
      const trimmed = currentSegment.trimStart();
      const trimOffset = currentSegment.length - trimmed.length;
      const finalText = trimmed.trimEnd();
      if (finalText.length > 0) {
        segments.push({
          text: finalText,
          startOffset: currentStartOffset + trimOffset,
          endOffset: currentOffset - (trimmed.length - finalText.length)
        });
      }
    }
    return segments;
  }
  splitByParagraphs(text) {
    return text.split(/\n\s*\n/).filter((p) => p.trim().length > 0);
  }
  splitLongParagraph(paragraph, startOffset) {
    const segments = [];
    const sentences = this.splitBySentences(paragraph);
    let currentSegment = "";
    let currentStartOffset = startOffset;
    let currentOffset = startOffset;
    for (const sentence of sentences) {
      if (currentSegment.length + sentence.length > this.maxSegmentLength) {
        if (currentSegment.length > 0) {
          const trimmed = currentSegment.trimStart();
          const trimOffset = currentSegment.length - trimmed.length;
          const finalText = trimmed.trimEnd();
          if (finalText.length > 0) {
            segments.push({
              text: finalText,
              startOffset: currentStartOffset + trimOffset,
              endOffset: currentOffset - (trimmed.length - finalText.length)
            });
          }
          currentSegment = "";
          currentStartOffset = currentOffset;
        }
        if (sentence.length > this.maxSegmentLength) {
          const chunks = this.splitByLength(sentence, this.maxSegmentLength);
          for (const chunk of chunks) {
            const trimmedChunk = chunk.trim();
            if (trimmedChunk.length > 0) {
              const chunkTrimOffset = chunk.length - chunk.trimStart().length;
              segments.push({
                text: trimmedChunk,
                startOffset: currentStartOffset + chunkTrimOffset,
                endOffset: currentStartOffset + chunk.length - (chunk.length - chunk.trimEnd().length)
              });
            }
            currentStartOffset += chunk.length;
            currentOffset = currentStartOffset;
          }
          continue;
        }
      }
      if (currentSegment.length === 0) {
        currentStartOffset = currentOffset;
      }
      currentSegment += sentence;
      currentOffset += sentence.length;
    }
    if (currentSegment.trim().length > 0) {
      const trimmed = currentSegment.trimStart();
      const trimOffset = currentSegment.length - trimmed.length;
      const finalText = trimmed.trimEnd();
      if (finalText.length > 0) {
        segments.push({
          text: finalText,
          startOffset: currentStartOffset + trimOffset,
          endOffset: currentOffset - (trimmed.length - finalText.length)
        });
      }
    }
    return segments;
  }
  splitBySentences(text) {
    const sentenceEndings = /([。！？；\n])/g;
    const parts = text.split(sentenceEndings);
    const sentences = [];
    for (let i = 0; i < parts.length; i += 2) {
      const sentence = parts[i] + (parts[i + 1] || "");
      if (sentence.trim().length > 0) {
        sentences.push(sentence);
      }
    }
    return sentences;
  }
  splitByLength(text, maxLength) {
    const chunks = [];
    for (let i = 0; i < text.length; i += maxLength) {
      chunks.push(text.substring(i, i + maxLength));
    }
    return chunks;
  }
};

// src/engines/aiDetector.ts
var AIDetector = class {
  constructor(settings) {
    this.settings = settings;
  }
  async detectSegment(segment) {
    if (!this.settings.apiKey) {
      throw new Error("API Key \u672A\u914D\u7F6E");
    }
    const prompt = this.buildPrompt(segment.text);
    try {
      const response = await this.callAPI(prompt);
      const parsed = this.parseResponse(response);
      const results = [];
      for (const r of parsed.results) {
        const matchResults = this.findWordInText(r.original, segment.text, segment.startOffset);
        for (const match of matchResults) {
          results.push({
            offset: match.offset,
            original: r.original,
            suggestions: [r.correct],
            reason: r.reason,
            source: "ai"
          });
        }
      }
      return results;
    } catch (error) {
      console.error("AI detection error:", error);
      throw error;
    }
  }
  async detectSegments(segments, onProgress) {
    const allResults = [];
    for (let i = 0; i < segments.length; i++) {
      if (onProgress) {
        onProgress(i + 1, segments.length);
      }
      try {
        const results = await this.detectSegment(segments[i]);
        allResults.push(...results);
      } catch (error) {
        console.error(`Error detecting segment ${i}:`, error);
      }
    }
    return allResults;
  }
  findWordInText(word, text, baseOffset) {
    const results = [];
    if (!word || word.length === 0) {
      return results;
    }
    let startIndex = 0;
    while (true) {
      const index = text.indexOf(word, startIndex);
      if (index === -1)
        break;
      results.push({
        offset: baseOffset + index
      });
      startIndex = index + 1;
    }
    return results;
  }
  buildPrompt(text) {
    return `\u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u4E2D\u6587\u6821\u5BF9\u52A9\u624B\u3002\u8BF7\u8BC6\u522B\u4EE5\u4E0B\u6587\u672C\u4E2D\u7684\u9519\u522B\u5B57\u3001\u97F3\u8FD1\u5B57\u3001\u5F62\u8FD1\u5B57\u8BEF\u7528\u3002

\u6587\u672C\uFF1A
${text}

\u8BF7\u4E25\u683C\u6309\u7167\u4EE5\u4E0B JSON \u6570\u7EC4\u683C\u5F0F\u8FD4\u56DE\u7ED3\u679C\uFF0C\u4E0D\u8981\u8FD4\u56DE\u4EFB\u4F55\u5176\u4ED6\u6587\u5B57\uFF1A
[{"original": "\u516C\u4F5C", "correct": "\u5DE5\u4F5C", "reason": "\u540C\u97F3\u5B57\u8BEF\u7528"}]

\u6CE8\u610F\uFF1A
1. original \u662F\u539F\u6587\u4E2D\u7684\u9519\u8BEF\u8BCD\uFF08\u5FC5\u987B\u5B8C\u5168\u5339\u914D\u539F\u6587\uFF09
2. correct \u662F\u5EFA\u8BAE\u7684\u6B63\u786E\u8BCD
3. reason \u662F\u7B80\u8981\u7684\u7EA0\u9519\u539F\u56E0\uFF08\u53EF\u9009\uFF09
4. \u5982\u679C\u6CA1\u6709\u53D1\u73B0\u9519\u8BEF\uFF0C\u8FD4\u56DE\u7A7A\u6570\u7EC4 []
5. \u4FDD\u6301\u539F\u610F\uFF0C\u4E0D\u8981\u6539\u52A8\u6587\u5B66\u6027\u4FEE\u8F9E\u3001\u4E13\u6709\u540D\u8BCD\u3001\u4EBA\u540D\u5730\u540D
6. \u53EA\u8FD4\u56DE\u786E\u5B9A\u662F\u9519\u522B\u5B57\u7684\uFF0C\u4E0D\u786E\u5B9A\u7684\u4E0D\u8FD4\u56DE
7. \u53EA\u8FD4\u56DE JSON \u6570\u7EC4\uFF0C\u4E0D\u8981\u6709\u4EFB\u4F55\u5176\u4ED6\u8F93\u51FA`;
  }
  async callAPI(prompt) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.settings.timeout);
    try {
      const response = await fetch(this.settings.apiEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.settings.apiKey}`
        },
        body: JSON.stringify({
          model: this.settings.modelName,
          messages: [
            {
              role: "system",
              content: "\u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u4E2D\u6587\u6821\u5BF9\u52A9\u624B\uFF0C\u4E13\u95E8\u8BC6\u522B\u6587\u672C\u4E2D\u7684\u9519\u522B\u5B57\u3002\u4F60\u53EA\u8FD4\u56DE JSON \u683C\u5F0F\u7684\u7ED3\u679C\uFF0C\u4E0D\u8FD4\u56DE\u4EFB\u4F55\u5176\u4ED6\u5185\u5BB9\u3002"
            },
            {
              role: "user",
              content: prompt
            }
          ],
          temperature: 0.1,
          max_tokens: 2e3
        }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API \u8BF7\u6C42\u5931\u8D25: ${response.status} - ${errorText}`);
      }
      const data = await response.json();
      if (!data.choices || !data.choices[0] || !data.choices[0].message) {
        throw new Error("API \u8FD4\u56DE\u683C\u5F0F\u9519\u8BEF");
      }
      return data.choices[0].message.content;
    } catch (error) {
      clearTimeout(timeoutId);
      if (error instanceof Error && error.name === "AbortError") {
        throw new Error("API \u8BF7\u6C42\u8D85\u65F6");
      }
      throw error;
    }
  }
  parseResponse(response) {
    try {
      let jsonStr = response.trim();
      const jsonMatch = jsonStr.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        jsonStr = jsonMatch[0];
      }
      const results = JSON.parse(jsonStr);
      if (!Array.isArray(results)) {
        throw new Error("\u8FD4\u56DE\u7ED3\u679C\u4E0D\u662F\u6570\u7EC4");
      }
      const validResults = results.filter(
        (r) => typeof r.original === "string" && typeof r.correct === "string" && r.original.length > 0 && r.correct.length > 0
      );
      return { results: validResults };
    } catch (error) {
      console.error("Failed to parse AI response:", response);
      return { results: [] };
    }
  }
  updateSettings(settings) {
    this.settings = settings;
  }
};

// src/detector/scheduler.ts
var DetectionScheduler = class {
  constructor(settings, app) {
    this.onProgress = null;
    this.settings = settings;
    this.textExtractor = new TextExtractor(app);
    this.textCleaner = new TextCleaner();
    this.textSegmenter = new TextSegmenter(settings.maxSegmentLength);
    this.aiDetector = new AIDetector(settings);
  }
  setProgressCallback(callback) {
    this.onProgress = callback;
  }
  async detect() {
    this.reportProgress({ status: "detecting", currentStep: "\u63D0\u53D6\u6587\u672C..." });
    const extractionResult = this.textExtractor.extractText();
    if (!extractionResult) {
      throw new Error("\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u6863\u5185\u5BB9");
    }
    const originalText = extractionResult.text;
    const hasSelection = extractionResult.hasSelection;
    const selectionRange = extractionResult.selectionRange;
    this.reportProgress({ status: "detecting", currentStep: "\u6E05\u6D17\u6587\u672C..." });
    const cleanResult = this.textCleaner.clean(originalText);
    const cleanedText = cleanResult.text;
    const mapper = new OffsetMapper(cleanResult.mappings);
    const allResults = [];
    if (this.settings.aiEngineEnabled && this.settings.apiKey) {
      this.reportProgress({ status: "detecting", currentStep: "\u51C6\u5907 AI \u68C0\u6D4B..." });
      const segments = this.textSegmenter.segment(cleanedText);
      if (segments.length > 0) {
        this.reportProgress({
          status: "detecting",
          currentStep: "AI \u5F15\u64CE\u68C0\u6D4B\u4E2D...",
          aiProgress: { current: 0, total: segments.length }
        });
        try {
          const aiResults = await this.aiDetector.detectSegments(segments, (current, total) => {
            this.reportProgress({
              status: "detecting",
              currentStep: "AI \u5F15\u64CE\u68C0\u6D4B\u4E2D...",
              aiProgress: { current, total }
            });
          });
          for (const result of aiResults) {
            if (!this.settings.ignoredWords.includes(result.original)) {
              const originalOffset = mapper.cleanOffsetToOriginal(result.offset);
              allResults.push({
                ...result,
                offset: originalOffset
              });
            }
          }
        } catch (error) {
          console.error("AI detection error:", error);
          new import_obsidian4.Notice("AI \u68C0\u6D4B\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5 API \u914D\u7F6E");
        }
      }
    }
    allResults.sort((a, b) => a.offset - b.offset);
    if (hasSelection && selectionRange) {
      return allResults.filter(
        (r) => r.offset >= selectionRange.from && r.offset < selectionRange.to
      );
    }
    return allResults;
  }
  reportProgress(progress) {
    if (this.onProgress) {
      this.onProgress(progress);
    }
  }
  updateSettings(settings) {
    this.settings = settings;
    this.textSegmenter = new TextSegmenter(settings.maxSegmentLength);
    this.aiDetector.updateSettings(settings);
  }
};

// src/main.ts
var CSCPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
    this.scheduler = null;
    this.detectionResults = [];
  }
  async onload() {
    await this.loadSettings();
    this.scheduler = new DetectionScheduler(this.settings, this.app);
    this.registerView(VIEW_TYPE_CSC, (leaf) => {
      this.view = new CSCView(leaf, this);
      return this.view;
    });
    this.addRibbonIcon("spell-check", "\u4E2D\u6587\u9519\u522B\u5B57\u68C0\u6D4B", () => {
      this.activateView();
    });
    this.addCommand({
      id: "check-chinese-typos",
      name: "\u68C0\u6D4B\u5F53\u524D\u6587\u6863\u9519\u522B\u5B57",
      callback: () => {
        this.startDetection();
      }
    });
    this.addSettingTab(new CSCSettingTab(this.app, this));
  }
  onunload() {
    if (this.view) {
      this.view = null;
    }
    this.scheduler = null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.scheduler) {
      this.scheduler.updateSettings(this.settings);
    }
  }
  activateView() {
    var _a;
    const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CSC);
    if (leaf.length > 0) {
      this.app.workspace.revealLeaf(leaf[0]);
      return;
    }
    (_a = this.app.workspace.getRightLeaf(false)) == null ? void 0 : _a.setViewState({
      type: VIEW_TYPE_CSC,
      active: true
    });
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (activeView) {
      return activeView;
    }
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian5.MarkdownView && view.getMode() === "source") {
        return view;
      }
    }
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian5.MarkdownView) {
        return view;
      }
    }
    return null;
  }
  async startDetection() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian5.Notice("\u6CA1\u6709\u6253\u5F00\u7684\u6587\u6863");
      return;
    }
    const mdView = this.getMarkdownView();
    if (!mdView) {
      new import_obsidian5.Notice("\u5F53\u524D\u89C6\u56FE\u4E0D\u662F Markdown \u7F16\u8F91\u5668");
      return;
    }
    this.activateView();
    if (!this.scheduler) {
      this.scheduler = new DetectionScheduler(this.settings, this.app);
    }
    if (this.view) {
      this.view.setStatus("detecting");
    }
    try {
      this.detectionResults = await this.scheduler.detect();
      if (this.view) {
        this.view.setResults(this.detectionResults);
        this.view.setStatus("completed");
      }
      if (this.detectionResults.length === 0) {
        new import_obsidian5.Notice("\u592A\u68D2\u4E86\uFF01\u6CA1\u6709\u53D1\u73B0\u9519\u522B\u5B57");
      } else {
        new import_obsidian5.Notice(`\u53D1\u73B0 ${this.detectionResults.length} \u5904\u53EF\u80FD\u7684\u9519\u522B\u5B57`);
      }
    } catch (error) {
      console.error("Detection error:", error);
      if (this.view) {
        this.view.setStatus("error", error instanceof Error ? error.message : "\u68C0\u6D4B\u5931\u8D25");
      }
      new import_obsidian5.Notice("\u68C0\u6D4B\u5931\u8D25: " + (error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"));
    }
  }
  applyFix(offset, original, replacement) {
    const editor = this.getEditor();
    if (!editor) {
      new import_obsidian5.Notice("\u65E0\u6CD5\u83B7\u53D6\u7F16\u8F91\u5668");
      return false;
    }
    try {
      const from = editor.offsetToPos(offset);
      const to = editor.offsetToPos(offset + original.length);
      const currentText = editor.getRange(from, to);
      if (currentText !== original) {
        console.log(`\u6587\u672C\u4E0D\u5339\u914D: \u671F\u671B "${original}", \u5B9E\u9645 "${currentText}", offset: ${offset}`);
        new import_obsidian5.Notice("\u6587\u672C\u5DF2\u88AB\u4FEE\u6539\u6216\u4F4D\u7F6E\u504F\u79FB\uFF0C\u8BF7\u91CD\u65B0\u68C0\u6D4B");
        return false;
      }
      editor.replaceRange(replacement, from, to);
      this.updateResultsAfterFix(offset, original.length, replacement.length);
      return true;
    } catch (error) {
      console.error("Apply fix error:", error);
      new import_obsidian5.Notice("\u4FEE\u590D\u5931\u8D25");
      return false;
    }
  }
  applyAllFixes() {
    const editor = this.getEditor();
    if (!editor) {
      new import_obsidian5.Notice("\u65E0\u6CD5\u83B7\u53D6\u7F16\u8F91\u5668");
      return 0;
    }
    const sortedResults = [...this.detectionResults].sort((a, b) => b.offset - a.offset);
    let successCount = 0;
    for (const result of sortedResults) {
      if (result.suggestions.length === 0)
        continue;
      const replacement = result.suggestions[0];
      const from = editor.offsetToPos(result.offset);
      const to = editor.offsetToPos(result.offset + result.original.length);
      try {
        const currentText = editor.getRange(from, to);
        if (currentText === result.original) {
          editor.replaceRange(replacement, from, to);
          successCount++;
        }
      } catch (error) {
        console.error("Apply fix error:", error);
      }
    }
    this.detectionResults = [];
    if (this.view) {
      this.view.setResults([]);
    }
    new import_obsidian5.Notice(`\u5DF2\u4FEE\u590D ${successCount} \u5904\u9519\u522B\u5B57`);
    return successCount;
  }
  updateResultsAfterFix(fixedOffset, originalLength, replacementLength) {
    const lengthDiff = replacementLength - originalLength;
    this.detectionResults = this.detectionResults.filter(
      (r) => !(r.offset === fixedOffset && r.original.length === originalLength)
    );
    for (const result of this.detectionResults) {
      if (result.offset > fixedOffset) {
        result.offset += lengthDiff;
      }
    }
    if (this.view) {
      this.view.setResults(this.detectionResults);
    }
  }
  getEditor() {
    const mdView = this.getMarkdownView();
    return (mdView == null ? void 0 : mdView.editor) || null;
  }
  getResults() {
    return this.detectionResults;
  }
};
