/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CSCPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/types.ts
var CATEGORY_LABELS = {
  typo: "\u9519\u522B\u5B57",
  punctuation: "\u6807\u70B9",
  grammar: "\u8BED\u6CD5"
};
var MODE_LABELS = {
  quick: "\u5FEB\u901F\u6A21\u5F0F",
  standard: "\u6807\u51C6\u6A21\u5F0F",
  deep: "\u6DF1\u5EA6\u6A21\u5F0F"
};
var MODE_DESCRIPTIONS = {
  quick: "\u4EC5\u68C0\u6D4B\u9519\u522B\u5B57\uFF08\u97F3\u8FD1\u5B57\u3001\u5F62\u8FD1\u5B57\u3001\u7B14\u8BEF\uFF09",
  standard: "\u68C0\u6D4B\u9519\u522B\u5B57 + \u6807\u70B9\u7B26\u53F7 + \u8BED\u6CD5\u9519\u8BEF",
  deep: "\u5168\u90E8\u68C0\u6D4B + \u8868\u8FBE\u4F18\u5316\u5EFA\u8BAE"
};
var LICENSE_LABELS = {
  basic: "\u57FA\u7840\u7248",
  full: "\u6B63\u5F0F\u7248"
};
var LICENSE_DESCRIPTIONS = {
  basic: "\u5FEB\u901F\u6A21\u5F0F\u68C0\u6D4B\uFF0C\u9002\u5408\u65E5\u5E38\u7B80\u5355\u6821\u5BF9",
  full: "\u5168\u90E8\u68C0\u6D4B\u6A21\u5F0F\uFF0C\u5305\u542B\u6807\u70B9\u3001\u8BED\u6CD5\u3001\u8868\u8FBE\u4F18\u5316"
};
var DEFAULT_SETTINGS = {
  apiKey: "",
  apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
  modelName: "deepseek-chat",
  ignoredWords: [],
  maxSegmentLength: 1500,
  timeout: 3e4,
  detectionMode: "quick",
  licenseType: "basic",
  activationCode: "",
  activatedAt: ""
};

// src/services/ActivationService.ts
var LOCAL_STORAGE_KEY = "csc_license";
var API_ENDPOINT = "https://kbfwajzlaswbqesgxedu.supabase.co/rest/v1/activation_codes_proofreader";
var API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZndhanpsYXN3YnFlc2d4ZWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjU5MjYsImV4cCI6MjA2MjYwMTkyNn0.RyoKxCOwAzGnwD2B1mjm2s9IOb1btKcrN94jf2RtPbQ";
var ActivationService = class {
  static isFullVersion(licenseType) {
    return licenseType === "full";
  }
  static isBasicVersion(licenseType) {
    return licenseType === "basic";
  }
  checkLocalLicenseStatus() {
    try {
      const storedLicense = localStorage.getItem(LOCAL_STORAGE_KEY);
      if (storedLicense) {
        const licenseInfo = JSON.parse(storedLicense);
        if (licenseInfo.licenseType) {
          return licenseInfo.licenseType;
        }
      }
    } catch (error) {
    }
    return "basic";
  }
  getLocalLicenseInfo() {
    try {
      const storedLicense = localStorage.getItem(LOCAL_STORAGE_KEY);
      if (storedLicense) {
        return JSON.parse(storedLicense);
      }
    } catch (error) {
    }
    return null;
  }
  saveLicenseToLocalStorage(licenseInfo) {
    try {
      localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(licenseInfo));
    } catch (error) {
    }
  }
  clearLicenseFromLocalStorage() {
    try {
      localStorage.removeItem(LOCAL_STORAGE_KEY);
    } catch (error) {
    }
  }
  async activate(activationCode) {
    if (!activationCode || activationCode.trim().length === 0) {
      return {
        success: false,
        message: "\u8BF7\u8F93\u5165\u6FC0\u6D3B\u7801"
      };
    }
    const trimmedCode = activationCode.trim();
    try {
      const url = `${API_ENDPOINT}?code=eq.${encodeURIComponent(trimmedCode)}&select=*`;
      const response = await fetch(url, {
        method: "GET",
        headers: {
          "apikey": API_KEY,
          "Authorization": `Bearer ${API_KEY}`,
          "Content-Type": "application/json"
        }
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          success: false,
          message: `\u670D\u52A1\u5668\u9519\u8BEF: HTTP ${response.status}`
        };
      }
      const data = await response.json();
      if (!data || data.length === 0) {
        return {
          success: false,
          message: "\u6FC0\u6D3B\u7801\u65E0\u6548\uFF0C\u8BF7\u68C0\u67E5\u540E\u91CD\u8BD5"
        };
      }
      const codeRecord = data[0];
      if (codeRecord.status === "used") {
        return {
          success: false,
          message: "\u8BE5\u6FC0\u6D3B\u7801\u5DF2\u88AB\u4F7F\u7528"
        };
      }
      const updateUrl = `${API_ENDPOINT}?code=eq.${encodeURIComponent(trimmedCode)}`;
      const updateResponse = await fetch(updateUrl, {
        method: "PATCH",
        headers: {
          "apikey": API_KEY,
          "Authorization": `Bearer ${API_KEY}`,
          "Content-Type": "application/json",
          "Prefer": "return=minimal"
        },
        body: JSON.stringify({
          status: "used",
          used_at: (/* @__PURE__ */ new Date()).toISOString()
        })
      });
      if (!updateResponse.ok) {
        return {
          success: false,
          message: "\u6FC0\u6D3B\u5931\u8D25\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5"
        };
      }
      const licenseInfo = {
        licenseType: "full",
        activationCode: trimmedCode,
        activatedAt: (/* @__PURE__ */ new Date()).toISOString()
      };
      this.saveLicenseToLocalStorage(licenseInfo);
      return {
        success: true,
        message: "\u6FC0\u6D3B\u6210\u529F\uFF01\u5DF2\u5347\u7EA7\u4E3A\u6B63\u5F0F\u7248",
        licenseType: "full"
      };
    } catch (error) {
      if (error instanceof Error) {
        if (error.message.includes("fetch")) {
          return {
            success: false,
            message: "\u7F51\u7EDC\u8FDE\u63A5\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u540E\u91CD\u8BD5"
          };
        }
        return {
          success: false,
          message: `\u6FC0\u6D3B\u5931\u8D25: ${error.message}`
        };
      }
      return {
        success: false,
        message: "\u6FC0\u6D3B\u5931\u8D25\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5"
      };
    }
  }
  deactivate() {
    this.clearLicenseFromLocalStorage();
  }
  isValidActivationCode(code) {
    if (!code || typeof code !== "string") {
      return false;
    }
    const trimmed = code.trim();
    return trimmed.length >= 8 && trimmed.length <= 64;
  }
};
var activationService = new ActivationService();

// src/settings.ts
var CSCSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.testButton = null;
    this.testStatus = null;
    this.activationStatus = null;
    this.activationButton = null;
    this.modeDropdown = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u4E2D\u6587\u6821\u5BF9\u8BBE\u7F6E" });
    this.renderLicenseSection(containerEl);
    this.renderApiSettings(containerEl);
    this.renderEngineSettings(containerEl);
    this.renderIgnoredWordsSettings(containerEl);
    this.renderAdvancedSettings(containerEl);
  }
  renderLicenseSection(containerEl) {
    containerEl.createEl("h3", { text: "\u8BB8\u53EF\u8BC1" });
    const licenseType = this.plugin.settings.licenseType;
    const isFullVersion = ActivationService.isFullVersion(licenseType);
    const statusContainer = containerEl.createDiv({ cls: "csc-license-status-container" });
    this.activationStatus = statusContainer.createDiv({ cls: "csc-license-status" });
    this.renderLicenseStatus(this.activationStatus, licenseType);
    if (isFullVersion) {
      const licenseInfo = activationService.getLocalLicenseInfo();
      if (licenseInfo == null ? void 0 : licenseInfo.activatedAt) {
        const activatedDate = new Date(licenseInfo.activatedAt).toLocaleDateString("zh-CN");
        new import_obsidian.Setting(containerEl).setName("\u6FC0\u6D3B\u65F6\u95F4").setDesc(activatedDate);
      }
    } else {
      new import_obsidian.Setting(containerEl).setName("\u6FC0\u6D3B\u7801").setDesc("\u8F93\u5165\u6FC0\u6D3B\u7801\u5347\u7EA7\u4E3A\u6B63\u5F0F\u7248\uFF0C\u89E3\u9501\u5168\u90E8\u68C0\u6D4B\u6A21\u5F0F").addText(
        (text) => text.setPlaceholder("\u8BF7\u8F93\u5165\u6FC0\u6D3B\u7801").setValue(this.plugin.settings.activationCode).onChange(async (value) => {
          this.plugin.settings.activationCode = value;
          await this.plugin.saveSettings();
        })
      ).addButton((btn) => {
        btn.setButtonText("\u6FC0\u6D3B");
        btn.setClass("csc-activate-btn");
        btn.onClick(async () => {
          await this.handleActivation();
        });
        this.activationButton = btn.buttonEl;
      });
      const featureComparison = containerEl.createDiv({ cls: "csc-feature-comparison" });
      this.renderFeatureComparison(featureComparison);
      const purchaseLink = containerEl.createDiv({ cls: "csc-purchase-link" });
      purchaseLink.createEl("a", {
        text: "\u83B7\u53D6\u6B63\u5F0F\u7248\u6FC0\u6D3B\u7801 \u2192",
        href: "http://www.moaono.com/obsidian-storyweaver/proofreader.html",
        attr: { target: "_blank" }
      });
    }
  }
  renderLicenseStatus(container, licenseType) {
    container.empty();
    const isFullVersion = ActivationService.isFullVersion(licenseType);
    const statusClass = isFullVersion ? "csc-license-full" : "csc-license-basic";
    const statusText = isFullVersion ? "\u2713 \u6B63\u5F0F\u7248" : "\u57FA\u7840\u7248";
    container.createEl("span", {
      cls: `csc-license-badge ${statusClass}`,
      text: statusText
    });
    container.createEl("span", {
      cls: "csc-license-desc",
      text: LICENSE_DESCRIPTIONS[licenseType]
    });
  }
  renderFeatureComparison(container) {
    container.createEl("div", { cls: "csc-feature-comparison-title", text: "\u7248\u672C\u529F\u80FD\u5BF9\u6BD4" });
    const table = container.createEl("table", { cls: "csc-feature-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "\u529F\u80FD" });
    headerRow.createEl("th", { text: "\u57FA\u7840\u7248" });
    headerRow.createEl("th", { text: "\u6B63\u5F0F\u7248" });
    const tbody = table.createEl("tbody");
    const features = [
      { name: "\u9519\u522B\u5B57\u68C0\u6D4B", basic: "\u2713", full: "\u2713" },
      { name: "\u6807\u70B9\u7B26\u53F7\u68C0\u67E5", basic: "-", full: "\u2713" },
      { name: "\u8BED\u6CD5\u9519\u8BEF\u68C0\u6D4B", basic: "-", full: "\u2713" },
      { name: "\u8868\u8FBE\u4F18\u5316\u5EFA\u8BAE", basic: "-", full: "\u2713" },
      { name: "\u7F16\u8F91\u5668\u9AD8\u4EAE", basic: "\u2713", full: "\u2713" },
      { name: "\u4E0A\u4E0B\u6587\u9884\u89C8", basic: "\u2713", full: "\u2713" }
    ];
    for (const feature of features) {
      const row = tbody.createEl("tr");
      row.createEl("td", { text: feature.name });
      row.createEl("td", {
        text: feature.basic,
        cls: feature.basic === "\u2713" ? "csc-feature-available" : "csc-feature-unavailable"
      });
      row.createEl("td", {
        text: feature.full,
        cls: feature.full === "\u2713" ? "csc-feature-available" : "csc-feature-unavailable"
      });
    }
  }
  async handleActivation() {
    const activationCode = this.plugin.settings.activationCode;
    if (!activationCode || activationCode.trim().length === 0) {
      new import_obsidian.Notice("\u8BF7\u8F93\u5165\u6FC0\u6D3B\u7801");
      return;
    }
    if (this.activationButton) {
      this.activationButton.setAttribute("disabled", "true");
      this.activationButton.textContent = "\u6FC0\u6D3B\u4E2D...";
    }
    try {
      const result = await activationService.activate(activationCode);
      if (result.success) {
        this.plugin.settings.licenseType = result.licenseType || "full";
        this.plugin.settings.activatedAt = (/* @__PURE__ */ new Date()).toISOString();
        await this.plugin.saveSettings();
        new import_obsidian.Notice(result.message);
        this.display();
      } else {
        new import_obsidian.Notice(result.message);
        if (this.activationButton) {
          this.activationButton.removeAttribute("disabled");
          this.activationButton.textContent = "\u6FC0\u6D3B";
        }
      }
    } catch (error) {
      console.error("Activation error:", error);
      new import_obsidian.Notice("\u6FC0\u6D3B\u5931\u8D25\uFF0C\u8BF7\u7A0D\u540E\u91CD\u8BD5");
      if (this.activationButton) {
        this.activationButton.removeAttribute("disabled");
        this.activationButton.textContent = "\u6FC0\u6D3B";
      }
    }
  }
  renderApiSettings(containerEl) {
    containerEl.createEl("h3", { text: "API \u914D\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u8F93\u5165\u4F60\u7684 AI \u670D\u52A1 API Key\uFF08\u652F\u6301 DeepSeek\u3001OpenAI \u517C\u5BB9\u63A5\u53E3\uFF09").addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API \u7AEF\u70B9").setDesc("AI \u670D\u52A1\u7684 API \u7AEF\u70B9\u5730\u5740").addText(
      (text) => text.setPlaceholder("https://api.deepseek.com/v1/chat/completions").setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
        this.plugin.settings.apiEndpoint = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B\u540D\u79F0").setDesc("\u4F7F\u7528\u7684\u6A21\u578B\u540D\u79F0").addText(
      (text) => text.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.modelName).onChange(async (value) => {
        this.plugin.settings.modelName = value;
        await this.plugin.saveSettings();
      })
    );
    const testSetting = new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u6D4B\u8BD5 API \u914D\u7F6E\u662F\u5426\u6B63\u786E");
    this.testStatus = testSetting.controlEl.createDiv({ cls: "csc-test-status" });
    testSetting.addButton((btn) => {
      btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
      btn.setClass("csc-test-btn");
      btn.onClick(async () => {
        await this.testConnection(btn);
      });
      this.testButton = btn.buttonEl;
    });
  }
  async testConnection(btn) {
    var _a;
    const { apiKey, apiEndpoint, modelName, timeout } = this.plugin.settings;
    if (!apiKey) {
      this.updateTestStatus("error", "\u8BF7\u5148\u8F93\u5165 API Key");
      return;
    }
    if (!apiEndpoint) {
      this.updateTestStatus("error", "\u8BF7\u5148\u8F93\u5165 API \u7AEF\u70B9");
      return;
    }
    btn.setDisabled(true);
    btn.setButtonText("\u6D4B\u8BD5\u4E2D...");
    this.updateTestStatus("testing", "\u6B63\u5728\u6D4B\u8BD5\u8FDE\u63A5...");
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeout);
    try {
      const response = await fetch(apiEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: modelName,
          messages: [
            {
              role: "user",
              content: "\u4F60\u597D"
            }
          ],
          max_tokens: 10
        }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      if (!response.ok) {
        const errorText = await response.text();
        let errorMsg = `HTTP ${response.status}`;
        try {
          const errorJson = JSON.parse(errorText);
          if ((_a = errorJson.error) == null ? void 0 : _a.message) {
            errorMsg = errorJson.error.message;
          }
        } catch (e) {
        }
        this.updateTestStatus("error", `\u8FDE\u63A5\u5931\u8D25: ${errorMsg}`);
        return;
      }
      const data = await response.json();
      if (data.choices && data.choices.length > 0) {
        this.updateTestStatus("success", "\u8FDE\u63A5\u6210\u529F\uFF01API \u914D\u7F6E\u6B63\u786E");
        new import_obsidian.Notice("API \u8FDE\u63A5\u6D4B\u8BD5\u6210\u529F");
      } else {
        this.updateTestStatus("error", "\u54CD\u5E94\u683C\u5F0F\u5F02\u5E38\uFF0C\u8BF7\u68C0\u67E5\u6A21\u578B\u540D\u79F0");
      }
    } catch (error) {
      clearTimeout(timeoutId);
      if (error instanceof Error) {
        if (error.name === "AbortError") {
          this.updateTestStatus("error", "\u8FDE\u63A5\u8D85\u65F6\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u6216\u589E\u52A0\u8D85\u65F6\u65F6\u95F4");
        } else {
          this.updateTestStatus("error", `\u8FDE\u63A5\u5931\u8D25: ${error.message}`);
        }
      } else {
        this.updateTestStatus("error", "\u8FDE\u63A5\u5931\u8D25: \u672A\u77E5\u9519\u8BEF");
      }
    } finally {
      btn.setDisabled(false);
      btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
    }
  }
  updateTestStatus(status, message) {
    if (!this.testStatus)
      return;
    this.testStatus.empty();
    this.testStatus.className = "csc-test-status";
    this.testStatus.createSpan({
      cls: `csc-test-status-${status}`,
      text: message
    });
  }
  renderEngineSettings(containerEl) {
    containerEl.createEl("h3", { text: "\u68C0\u6D4B\u914D\u7F6E" });
    const isFullVersion = ActivationService.isFullVersion(this.plugin.settings.licenseType);
    const modeSetting = new import_obsidian.Setting(containerEl).setName("\u68C0\u6D4B\u6A21\u5F0F").setDesc("\u9009\u62E9\u6821\u5BF9\u7684\u68C0\u6D4B\u8303\u56F4\u548C\u6DF1\u5EA6").addDropdown((dropdown) => {
      this.modeDropdown = dropdown;
      dropdown.addOption("quick", MODE_LABELS.quick);
      if (isFullVersion) {
        dropdown.addOption("standard", MODE_LABELS.standard);
        dropdown.addOption("deep", MODE_LABELS.deep);
      }
      dropdown.setValue(this.plugin.settings.detectionMode).onChange(async (value) => {
        const selectedMode = value;
        if (!isFullVersion && selectedMode !== "quick") {
          new import_obsidian.Notice("\u6807\u51C6\u6A21\u5F0F\u548C\u6DF1\u5EA6\u6A21\u5F0F\u9700\u8981\u6B63\u5F0F\u7248");
          dropdown.setValue("quick");
          return;
        }
        this.plugin.settings.detectionMode = selectedMode;
        await this.plugin.saveSettings();
        this.updateModeDescription(containerEl, selectedMode);
      });
    });
    if (!isFullVersion) {
      modeSetting.setDesc("\u6807\u51C6\u6A21\u5F0F\u548C\u6DF1\u5EA6\u6A21\u5F0F\u9700\u8981\u6B63\u5F0F\u7248");
    }
    const modeDescEl = containerEl.createDiv({ cls: "csc-mode-desc" });
    this.renderModeDescription(modeDescEl, this.plugin.settings.detectionMode);
  }
  renderModeDescription(container, mode) {
    container.empty();
    const desc = MODE_DESCRIPTIONS[mode];
    container.createEl("div", { cls: "csc-mode-desc-content", text: desc });
    const features = container.createEl("div", { cls: "csc-mode-features" });
    switch (mode) {
      case "quick":
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-typo", text: "\u9519\u522B\u5B57" });
        break;
      case "standard":
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-typo", text: "\u9519\u522B\u5B57" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-punctuation", text: "\u6807\u70B9" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-grammar", text: "\u8BED\u6CD5" });
        break;
      case "deep":
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-typo", text: "\u9519\u522B\u5B57" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-punctuation", text: "\u6807\u70B9" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-grammar", text: "\u8BED\u6CD5" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-expression", text: "\u8868\u8FBE\u4F18\u5316" });
        break;
    }
  }
  updateModeDescription(containerEl, mode) {
    const existingDesc = containerEl.querySelector(".csc-mode-desc");
    if (existingDesc) {
      this.renderModeDescription(existingDesc, mode);
    }
  }
  renderIgnoredWordsSettings(containerEl) {
    containerEl.createEl("h3", { text: "\u5FFD\u7565\u8BCD\u5E93" });
    new import_obsidian.Setting(containerEl).setName("\u5FFD\u7565\u8BCD\u5217\u8868").setDesc("\u8FD9\u4E9B\u8BCD\u5C06\u4E0D\u4F1A\u88AB\u68C0\u6D4B\u4E3A\u9519\u522B\u5B57\uFF08\u6BCF\u884C\u4E00\u4E2A\u8BCD\uFF09").addTextArea(
      (text) => text.setPlaceholder("\u8F93\u5165\u8981\u5FFD\u7565\u7684\u8BCD\u6C47...").setValue(this.plugin.settings.ignoredWords.join("\n")).onChange(async (value) => {
        this.plugin.settings.ignoredWords = value.split("\n").map((word) => word.trim()).filter((word) => word.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
  renderAdvancedSettings(containerEl) {
    containerEl.createEl("h3", { text: "\u9AD8\u7EA7\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u5206\u6BB5\u957F\u5EA6").setDesc("AI \u68C0\u6D4B\u65F6\u6BCF\u6BB5\u6587\u672C\u7684\u6700\u5927\u5B57\u7B26\u6570\uFF08\u5EFA\u8BAE 1000-2000\uFF09").addSlider(
      (slider) => slider.setLimits(500, 3e3, 100).setValue(this.plugin.settings.maxSegmentLength).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxSegmentLength = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8BF7\u6C42\u8D85\u65F6").setDesc("API \u8BF7\u6C42\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09").addText(
      (text) => text.setValue(String(this.plugin.settings.timeout)).onChange(async (value) => {
        const timeout = parseInt(value, 10);
        if (!isNaN(timeout) && timeout > 0) {
          this.plugin.settings.timeout = timeout;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_CSC = "csc-view";
var CSCView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.status = "idle";
    this.errorMessage = "";
    this.containerDiv = null;
    this.originalText = "";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CSC;
  }
  getDisplayText() {
    return "\u4E2D\u6587\u6821\u5BF9";
  }
  getIcon() {
    return "spell-check";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setResults(results, originalText) {
    this.results = results;
    if (originalText !== void 0) {
      this.originalText = originalText;
    }
    this.applyFilter();
    this.render();
  }
  setOriginalText(text) {
    this.originalText = text;
  }
  setStatus(status, errorMessage) {
    this.status = status;
    this.errorMessage = errorMessage || "";
    this.render();
  }
  applyFilter() {
    if (this.activeFilter === "all") {
      this.filteredResults = [...this.results];
    } else {
      this.filteredResults = this.results.filter((r) => r.category === this.activeFilter);
    }
  }
  getCategoryCount(category) {
    if (category === "all")
      return this.results.length;
    return this.results.filter((r) => r.category === category).length;
  }
  getActiveCategories() {
    const categories = /* @__PURE__ */ new Set();
    this.results.forEach((r) => categories.add(r.category));
    return Array.from(categories);
  }
  extractContext(offset, length, contextLength = 20) {
    if (!this.originalText)
      return null;
    const beforeStart = Math.max(0, offset - contextLength);
    const before = this.originalText.slice(beforeStart, offset);
    const error = this.originalText.slice(offset, offset + length);
    const afterEnd = Math.min(this.originalText.length, offset + length + contextLength);
    const after = this.originalText.slice(offset + length, afterEnd);
    return { before, error, after };
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.createEl("div", { cls: "csc-container" }, (div) => {
      this.containerDiv = div;
      this.renderHeader(div);
      this.renderFilterBar(div);
      this.renderContent(div);
      this.renderFooter(div);
    });
  }
  renderHeader(container) {
    container.createEl("div", { cls: "csc-header" }, (header) => {
      header.createEl("div", { cls: "csc-header-top" }, (top) => {
        top.createEl("div", { cls: "csc-title-row" }, (titleRow) => {
          const iconEl = titleRow.createEl("div", { cls: "csc-title-icon" });
          (0, import_obsidian2.setIcon)(iconEl, "spell-check");
          titleRow.createEl("h3", { text: "\u4E2D\u6587\u6821\u5BF9", cls: "csc-title" });
        });
        const statusEl = top.createEl("div", { cls: "csc-status" });
        this.renderStatus(statusEl);
      });
      const isFullVersion = this.plugin.isFullVersion();
      const licenseLabel = LICENSE_LABELS[this.plugin.settings.licenseType];
      const licenseClass = isFullVersion ? "csc-license-full" : "csc-license-basic";
      header.createEl("div", { cls: `csc-license-indicator ${licenseClass}` }, (indicator) => {
        indicator.createEl("span", { text: licenseLabel });
      });
      const modeLabel = MODE_LABELS[this.plugin.settings.detectionMode] || "\u5FEB\u901F\u6A21\u5F0F";
      header.createEl("div", { cls: "csc-mode-indicator", text: modeLabel });
      header.createEl("button", {
        cls: "csc-detect-btn"
      }, (btn) => {
        if (this.status === "detecting") {
          btn.createEl("div", { cls: "csc-btn-spinner" });
          btn.createEl("span", { text: "\u68C0\u6D4B\u4E2D..." });
          btn.disabled = true;
        } else {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "search");
          btn.createEl("span", { text: "\u5F00\u59CB\u68C0\u6D4B" });
        }
        btn.addEventListener("click", () => {
          this.startDetection();
        });
      });
    });
  }
  renderFilterBar(container) {
    if (this.results.length === 0 || this.status !== "completed")
      return;
    container.createEl("div", { cls: "csc-filter-bar" }, (bar) => {
      bar.createEl("button", {
        cls: `csc-filter-btn ${this.activeFilter === "all" ? "csc-filter-active" : ""}`,
        text: `\u5168\u90E8 (${this.getCategoryCount("all")})`
      }, (btn) => {
        btn.addEventListener("click", () => {
          this.activeFilter = "all";
          this.applyFilter();
          this.render();
        });
      });
      const activeCategories = this.getActiveCategories();
      for (const cat of activeCategories) {
        const count = this.getCategoryCount(cat);
        bar.createEl("button", {
          cls: `csc-filter-btn csc-filter-${cat} ${this.activeFilter === cat ? "csc-filter-active" : ""}`,
          text: `${CATEGORY_LABELS[cat]} (${count})`
        }, (btn) => {
          btn.addEventListener("click", () => {
            this.activeFilter = cat;
            this.applyFilter();
            this.render();
          });
        });
      }
    });
  }
  renderStatus(container) {
    switch (this.status) {
      case "idle":
        container.createEl("span", {
          text: "\u51C6\u5907\u5C31\u7EEA",
          cls: "csc-status-badge csc-status-idle"
        });
        break;
      case "detecting":
        container.createEl("span", {
          text: "\u68C0\u6D4B\u4E2D",
          cls: "csc-status-badge csc-status-detecting"
        });
        break;
      case "completed":
        const count = this.results.length;
        if (count === 0) {
          container.createEl("span", {
            text: "\u672A\u53D1\u73B0\u95EE\u9898",
            cls: "csc-status-badge csc-status-success"
          });
        } else {
          container.createEl("span", {
            text: `\u53D1\u73B0 ${count} \u5904\u95EE\u9898`,
            cls: "csc-status-badge csc-status-warning"
          });
        }
        break;
      case "error":
        container.createEl("span", {
          text: "\u68C0\u6D4B\u5931\u8D25",
          cls: "csc-status-badge csc-status-error"
        });
        break;
    }
  }
  renderContent(container) {
    container.createEl("div", { cls: "csc-content" }, (content) => {
      if (this.status === "detecting") {
        this.renderLoading(content);
        return;
      }
      if (this.status === "error") {
        this.renderError(content);
        return;
      }
      if (this.results.length === 0 && this.status === "completed") {
        this.renderSuccess(content);
        return;
      }
      if (this.results.length === 0) {
        this.renderEmpty(content);
        return;
      }
      if (this.filteredResults.length === 0) {
        this.renderFilterEmpty(content);
        return;
      }
      this.renderResults(content);
    });
  }
  renderLoading(container) {
    container.createEl("div", { cls: "csc-loading" }, (loading) => {
      loading.createEl("div", { cls: "csc-loading-animation" }, (anim) => {
        for (let i = 0; i < 3; i++) {
          anim.createEl("div", { cls: "csc-loading-dot" });
        }
      });
      loading.createEl("div", { cls: "csc-loading-text" }, (text) => {
        text.createEl("span", { text: "AI \u6B63\u5728\u5206\u6790\u6587\u672C..." });
        text.createEl("span", { text: "\u8BF7\u7A0D\u5019", cls: "csc-loading-sub" });
      });
    });
  }
  renderError(container) {
    container.createEl("div", { cls: "csc-message csc-message-error" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "alert-circle");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "\u68C0\u6D4B\u5931\u8D25", cls: "csc-message-title" });
        content.createEl("div", { text: this.errorMessage || "\u8BF7\u68C0\u67E5 API \u914D\u7F6E\u540E\u91CD\u8BD5", cls: "csc-message-desc" });
      });
    });
  }
  renderSuccess(container) {
    container.createEl("div", { cls: "csc-message csc-message-success" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "check-circle");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "\u592A\u68D2\u4E86\uFF01", cls: "csc-message-title" });
        content.createEl("div", { text: "\u6CA1\u6709\u53D1\u73B0\u95EE\u9898", cls: "csc-message-desc" });
      });
    });
  }
  renderEmpty(container) {
    container.createEl("div", { cls: "csc-message csc-message-empty" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "file-text");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "\u51C6\u5907\u68C0\u6D4B", cls: "csc-message-title" });
        content.createEl("div", { text: "\u70B9\u51FB\u4E0A\u65B9\u6309\u94AE\u5F00\u59CB\u68C0\u6D4B\u5F53\u524D\u6587\u6863", cls: "csc-message-desc" });
      });
    });
  }
  renderFilterEmpty(container) {
    container.createEl("div", { cls: "csc-message csc-message-empty" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "filter");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "\u5F53\u524D\u7B5B\u9009\u65E0\u7ED3\u679C", cls: "csc-message-title" });
        content.createEl("div", { text: "\u8BE5\u5206\u7C7B\u4E0B\u6CA1\u6709\u68C0\u6D4B\u5230\u95EE\u9898", cls: "csc-message-desc" });
      });
    });
  }
  renderResults(container) {
    container.createEl("div", { cls: "csc-result-list" }, (list) => {
      this.filteredResults.forEach((result, index) => {
        this.renderResultCard(list, result, index);
      });
    });
  }
  renderResultCard(container, result, index) {
    const globalIndex = this.results.indexOf(result);
    container.createEl("div", { cls: "csc-result-card" }, (card) => {
      card.createEl("div", { cls: "csc-card-header" }, (header) => {
        header.createEl("div", { cls: "csc-card-index" }, (indexEl) => {
          indexEl.createEl("span", { text: String(globalIndex + 1) });
        });
        header.createEl("div", { cls: `csc-card-category csc-category-${result.category}` }, (catEl) => {
          catEl.createEl("span", { text: CATEGORY_LABELS[result.category] });
        });
      });
      const context = this.extractContext(result.offset, result.original.length);
      if (context) {
        card.createEl("div", { cls: "csc-card-context" }, (ctx) => {
          if (context.before) {
            ctx.createEl("span", { text: context.before, cls: "csc-context-before" });
          }
          ctx.createEl("span", { text: context.error, cls: "csc-context-error" });
          if (context.after) {
            ctx.createEl("span", { text: context.after, cls: "csc-context-after" });
          }
        });
      }
      card.createEl("div", { cls: "csc-card-error" }, (error) => {
        error.createEl("div", { cls: "csc-error-row" }, (row) => {
          row.createEl("span", { text: "\u539F\u6587\uFF1A", cls: "csc-error-label" });
          row.createEl("span", { text: result.original, cls: "csc-error-text" });
        });
        error.createEl("div", { cls: "csc-arrow" }, (arrow) => {
          (0, import_obsidian2.setIcon)(arrow, "arrow-down");
        });
        error.createEl("div", { cls: "csc-correct-row" }, (row) => {
          row.createEl("span", { text: "\u5EFA\u8BAE\uFF1A", cls: "csc-correct-label" });
          row.createEl("span", { text: result.suggestions[0], cls: "csc-correct-text" });
        });
      });
      if (result.reason) {
        card.createEl("div", { cls: "csc-card-reason" }, (reason) => {
          const iconEl = reason.createEl("div", { cls: "csc-reason-icon" });
          (0, import_obsidian2.setIcon)(iconEl, "info");
          reason.createEl("span", { text: result.reason });
        });
      }
      card.createEl("div", { cls: "csc-card-actions" }, (actions) => {
        result.suggestions.forEach((suggestion) => {
          actions.createEl("button", {
            text: `\u66FF\u6362\u4E3A\u300C${suggestion}\u300D`,
            cls: "csc-action-btn csc-action-apply"
          }, (btn) => {
            btn.addEventListener("click", () => {
              this.applyFix(result.offset, result.original, suggestion, globalIndex);
            });
          });
        });
        actions.createEl("button", {
          cls: "csc-action-btn csc-action-ignore"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon-small" }), "x");
          btn.createEl("span", { text: "\u5FFD\u7565" });
          btn.addEventListener("click", () => {
            this.ignoreWord(result.original, globalIndex);
          });
        });
      });
    });
  }
  renderFooter(container) {
    if (this.filteredResults.length === 0 && this.results.length === 0)
      return;
    container.createEl("div", { cls: "csc-footer" }, (footer) => {
      if (this.filteredResults.length > 0) {
        footer.createEl("button", {
          cls: "csc-footer-btn csc-footer-apply"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "check");
          btn.createEl("span", { text: `\u66FF\u6362\u7B5B\u9009\u7ED3\u679C (${this.filteredResults.length})` });
          btn.addEventListener("click", () => {
            this.applyFilteredFixes();
          });
        });
        footer.createEl("button", {
          cls: "csc-footer-btn csc-footer-ignore"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "x-circle");
          btn.createEl("span", { text: "\u5168\u90E8\u5FFD\u7565" });
          btn.addEventListener("click", () => {
            this.ignoreAllWords();
          });
        });
      }
      if (this.results.length > 0) {
        footer.createEl("button", {
          cls: "csc-footer-btn csc-footer-clear"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "eraser");
          btn.createEl("span", { text: "\u6E05\u9664\u9AD8\u4EAE" });
          btn.addEventListener("click", () => {
            this.clearHighlights();
          });
        });
      }
    });
  }
  startDetection() {
    this.activeFilter = "all";
    this.plugin.startDetection();
  }
  applyFix(offset, original, replacement, index) {
    const success = this.plugin.applyFix(offset, original, replacement);
    if (success) {
      this.results = this.plugin.getResults();
      this.originalText = this.plugin.getOriginalText() || this.originalText;
      this.applyFilter();
      this.render();
    }
  }
  ignoreWord(word, index) {
    if (!this.plugin.settings.ignoredWords.includes(word)) {
      this.plugin.settings.ignoredWords.push(word);
      this.plugin.saveSettings();
    }
    this.results.splice(index, 1);
    this.applyFilter();
    this.render();
  }
  applyFilteredFixes() {
    const editor = this.plugin.getEditor();
    if (!editor)
      return;
    const sortedResults = [...this.filteredResults].sort((a, b) => b.offset - a.offset);
    let successCount = 0;
    for (const result of sortedResults) {
      if (result.suggestions.length === 0)
        continue;
      const replacement = result.suggestions[0];
      const from = editor.offsetToPos(result.offset);
      const to = editor.offsetToPos(result.offset + result.original.length);
      try {
        const currentText = editor.getRange(from, to);
        if (currentText === result.original) {
          editor.replaceRange(replacement, from, to);
          successCount++;
        }
      } catch (error) {
        console.error("Apply fix error:", error);
      }
    }
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.originalText = "";
    this.render();
    new import_obsidian2.Notice(`\u5DF2\u4FEE\u590D ${successCount} \u5904\u95EE\u9898`);
  }
  ignoreAllWords() {
    this.results.forEach((result) => {
      if (!this.plugin.settings.ignoredWords.includes(result.original)) {
        this.plugin.settings.ignoredWords.push(result.original);
      }
    });
    this.plugin.saveSettings();
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.render();
  }
  clearHighlights() {
    this.plugin.clearAllHighlights();
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.render();
  }
};

// src/detector/scheduler.ts
var import_obsidian4 = require("obsidian");

// src/text/extractor.ts
var import_obsidian3 = require("obsidian");
var TextExtractor = class {
  constructor(app) {
    this.app = app;
  }
  extractText() {
    const mdView = this.getMarkdownView();
    if (!mdView) {
      return null;
    }
    const editor = mdView.editor;
    if (!editor) {
      return null;
    }
    const selection = editor.getSelection();
    if (selection && selection.length > 0) {
      const from = editor.posToOffset(editor.getCursor("from"));
      const to = editor.posToOffset(editor.getCursor("to"));
      return {
        text: selection,
        hasSelection: true,
        selectionRange: { from, to }
      };
    }
    return {
      text: editor.getValue(),
      hasSelection: false
    };
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (activeView) {
      return activeView;
    }
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView && view.getMode() === "source") {
        return view;
      }
    }
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView) {
        return view;
      }
    }
    return null;
  }
};

// src/text/cleaner.ts
var TextCleaner = class {
  clean(originalText) {
    let text = originalText;
    const mappings = [];
    let cleanOffset = 0;
    let originalOffset = 0;
    const processedText = this.processText(text, originalOffset, cleanOffset, mappings);
    return {
      text: processedText.text,
      mappings: processedText.mappings
    };
  }
  processText(text, startOriginalOffset, startCleanOffset, mappings) {
    let result = "";
    let cleanOffset = startCleanOffset;
    let originalOffset = startOriginalOffset;
    let i = 0;
    while (i < text.length) {
      const yamlResult = this.tryExtractYamlFrontMatter(text, i);
      if (yamlResult) {
        for (let j = 0; j < yamlResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += yamlResult.length;
        i += yamlResult.length;
        continue;
      }
      const codeBlockResult = this.tryExtractCodeBlock(text, i);
      if (codeBlockResult) {
        for (let j = 0; j < codeBlockResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += codeBlockResult.length;
        i += codeBlockResult.length;
        continue;
      }
      const inlineCodeResult = this.tryExtractInlineCode(text, i);
      if (inlineCodeResult) {
        for (let j = 0; j < inlineCodeResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += inlineCodeResult.length;
        i += inlineCodeResult.length;
        continue;
      }
      const htmlResult = this.tryExtractHtmlTag(text, i);
      if (htmlResult) {
        for (let j = 0; j < htmlResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += htmlResult.length;
        i += htmlResult.length;
        continue;
      }
      const linkResult = this.tryExtractLink(text, i);
      if (linkResult) {
        const displayText = linkResult.displayText;
        for (let j = 0; j < linkResult.urlPart.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += linkResult.urlPart.length;
        i += linkResult.urlPart.length;
        for (let j = 0; j < displayText.length; j++) {
          mappings.push({
            cleanOffset: cleanOffset + j,
            originalOffset: originalOffset + j
          });
        }
        result += displayText;
        cleanOffset += displayText.length;
        originalOffset += displayText.length;
        i += displayText.length;
        continue;
      }
      mappings.push({
        cleanOffset,
        originalOffset
      });
      result += text[i];
      cleanOffset++;
      originalOffset++;
      i++;
    }
    return { text: result, mappings };
  }
  tryExtractYamlFrontMatter(text, start) {
    if (start !== 0)
      return null;
    if (!text.startsWith("---", start))
      return null;
    const endIndex = text.indexOf("---", 3);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 3);
  }
  tryExtractCodeBlock(text, start) {
    if (!text.startsWith("```", start))
      return null;
    const endIndex = text.indexOf("```", start + 3);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 3);
  }
  tryExtractInlineCode(text, start) {
    if (text[start] !== "`")
      return null;
    if (text.startsWith("```", start))
      return null;
    const endIndex = text.indexOf("`", start + 1);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 1);
  }
  tryExtractHtmlTag(text, start) {
    if (text[start] !== "<")
      return null;
    const endIndex = text.indexOf(">", start);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 1);
  }
  tryExtractLink(text, start) {
    const linkRegex = /^\[([^\]]*)\]\(([^)]+)\)/;
    const match = text.substring(start).match(linkRegex);
    if (!match)
      return null;
    const fullMatch = match[0];
    const displayText = match[1];
    const urlPart = fullMatch.substring(fullMatch.indexOf("]("));
    return {
      urlPart: `](${match[2]})`,
      displayText
    };
  }
};

// src/text/mapper.ts
var OffsetMapper = class {
  constructor(mappings) {
    this.mappings = mappings;
  }
  cleanOffsetToOriginal(cleanOffset) {
    for (let i = 0; i < this.mappings.length; i++) {
      if (this.mappings[i].cleanOffset === cleanOffset) {
        return this.mappings[i].originalOffset;
      }
    }
    for (let i = this.mappings.length - 1; i >= 0; i--) {
      if (this.mappings[i].cleanOffset !== -1 && this.mappings[i].cleanOffset < cleanOffset) {
        const diff = cleanOffset - this.mappings[i].cleanOffset;
        return this.mappings[i].originalOffset + diff;
      }
    }
    return cleanOffset;
  }
  originalOffsetToClean(originalOffset) {
    for (let i = 0; i < this.mappings.length; i++) {
      if (this.mappings[i].originalOffset === originalOffset) {
        return this.mappings[i].cleanOffset;
      }
    }
    for (let i = this.mappings.length - 1; i >= 0; i--) {
      if (this.mappings[i].originalOffset < originalOffset) {
        const diff = originalOffset - this.mappings[i].originalOffset;
        const targetClean = this.mappings[i].cleanOffset + diff;
        if (targetClean >= 0) {
          return targetClean;
        }
      }
    }
    return originalOffset;
  }
  isValidCleanOffset(offset) {
    return offset >= 0 && offset < this.mappings.length;
  }
  isValidOriginalOffset(offset) {
    var _a;
    return this.mappings.some((m) => m.originalOffset === offset) || offset >= 0 && offset <= ((_a = this.mappings[this.mappings.length - 1]) == null ? void 0 : _a.originalOffset);
  }
};

// src/text/segmenter.ts
var TextSegmenter = class {
  constructor(maxSegmentLength = 1500) {
    this.maxSegmentLength = maxSegmentLength;
  }
  segment(text) {
    const paragraphs = this.splitByParagraphs(text);
    const segments = [];
    let currentSegment = "";
    let currentStartOffset = 0;
    let currentOffset = 0;
    for (const paragraph of paragraphs) {
      if (currentSegment.length + paragraph.length + 1 > this.maxSegmentLength) {
        if (currentSegment.length > 0) {
          const trimmed = currentSegment.trimStart();
          const trimOffset = currentSegment.length - trimmed.length;
          const finalText = trimmed.trimEnd();
          if (finalText.length > 0) {
            segments.push({
              text: finalText,
              startOffset: currentStartOffset + trimOffset,
              endOffset: currentOffset - (trimmed.length - finalText.length)
            });
          }
          currentSegment = "";
          currentStartOffset = currentOffset;
        }
        if (paragraph.length > this.maxSegmentLength) {
          const subSegments = this.splitLongParagraph(paragraph, currentStartOffset);
          segments.push(...subSegments);
          currentStartOffset = currentOffset + paragraph.length;
          currentOffset = currentStartOffset;
          continue;
        }
      }
      if (currentSegment.length > 0) {
        currentSegment += "\n";
        currentOffset++;
      }
      if (currentSegment.length === 0) {
        currentStartOffset = currentOffset;
      }
      currentSegment += paragraph;
      currentOffset += paragraph.length;
    }
    if (currentSegment.trim().length > 0) {
      const trimmed = currentSegment.trimStart();
      const trimOffset = currentSegment.length - trimmed.length;
      const finalText = trimmed.trimEnd();
      if (finalText.length > 0) {
        segments.push({
          text: finalText,
          startOffset: currentStartOffset + trimOffset,
          endOffset: currentOffset - (trimmed.length - finalText.length)
        });
      }
    }
    return segments;
  }
  splitByParagraphs(text) {
    return text.split(/\n\s*\n/).filter((p) => p.trim().length > 0);
  }
  splitLongParagraph(paragraph, startOffset) {
    const segments = [];
    const sentences = this.splitBySentences(paragraph);
    let currentSegment = "";
    let currentStartOffset = startOffset;
    let currentOffset = startOffset;
    for (const sentence of sentences) {
      if (currentSegment.length + sentence.length > this.maxSegmentLength) {
        if (currentSegment.length > 0) {
          const trimmed = currentSegment.trimStart();
          const trimOffset = currentSegment.length - trimmed.length;
          const finalText = trimmed.trimEnd();
          if (finalText.length > 0) {
            segments.push({
              text: finalText,
              startOffset: currentStartOffset + trimOffset,
              endOffset: currentOffset - (trimmed.length - finalText.length)
            });
          }
          currentSegment = "";
          currentStartOffset = currentOffset;
        }
        if (sentence.length > this.maxSegmentLength) {
          const chunks = this.splitByLength(sentence, this.maxSegmentLength);
          for (const chunk of chunks) {
            const trimmedChunk = chunk.trim();
            if (trimmedChunk.length > 0) {
              const chunkTrimOffset = chunk.length - chunk.trimStart().length;
              segments.push({
                text: trimmedChunk,
                startOffset: currentStartOffset + chunkTrimOffset,
                endOffset: currentStartOffset + chunk.length - (chunk.length - chunk.trimEnd().length)
              });
            }
            currentStartOffset += chunk.length;
            currentOffset = currentStartOffset;
          }
          continue;
        }
      }
      if (currentSegment.length === 0) {
        currentStartOffset = currentOffset;
      }
      currentSegment += sentence;
      currentOffset += sentence.length;
    }
    if (currentSegment.trim().length > 0) {
      const trimmed = currentSegment.trimStart();
      const trimOffset = currentSegment.length - trimmed.length;
      const finalText = trimmed.trimEnd();
      if (finalText.length > 0) {
        segments.push({
          text: finalText,
          startOffset: currentStartOffset + trimOffset,
          endOffset: currentOffset - (trimmed.length - finalText.length)
        });
      }
    }
    return segments;
  }
  splitBySentences(text) {
    const sentenceEndings = /([。！？；\n])/g;
    const parts = text.split(sentenceEndings);
    const sentences = [];
    for (let i = 0; i < parts.length; i += 2) {
      const sentence = parts[i] + (parts[i + 1] || "");
      if (sentence.trim().length > 0) {
        sentences.push(sentence);
      }
    }
    return sentences;
  }
  splitByLength(text, maxLength) {
    const chunks = [];
    for (let i = 0; i < text.length; i += maxLength) {
      chunks.push(text.substring(i, i + maxLength));
    }
    return chunks;
  }
};

// src/engines/aiDetector.ts
var CATEGORY_MAP = {
  typo: "typo",
  punctuation: "punctuation",
  grammar: "grammar"
};
var AIDetector = class {
  constructor(settings) {
    this.settings = settings;
  }
  async detectSegment(segment) {
    if (!this.settings.apiKey) {
      throw new Error("API Key \u672A\u914D\u7F6E");
    }
    const prompt = this.buildPrompt(segment.text, this.settings.detectionMode);
    try {
      const response = await this.callAPI(prompt);
      const parsed = this.parseResponse(response);
      const results = [];
      for (const r of parsed.results) {
        const matchResults = this.findWordInText(r.original, segment.text, segment.startOffset);
        const category = this.normalizeCategory(r.category);
        for (const match of matchResults) {
          results.push({
            offset: match.offset,
            original: r.original,
            suggestions: [r.correct],
            reason: r.reason,
            source: "ai",
            category
          });
        }
      }
      return results;
    } catch (error) {
      console.error("AI detection error:", error);
      throw error;
    }
  }
  async detectSegments(segments, onProgress) {
    const allResults = [];
    for (let i = 0; i < segments.length; i++) {
      if (onProgress) {
        onProgress(i + 1, segments.length);
      }
      try {
        const results = await this.detectSegment(segments[i]);
        allResults.push(...results);
      } catch (error) {
        console.error(`Error detecting segment ${i}:`, error);
      }
    }
    return allResults;
  }
  normalizeCategory(raw) {
    if (!raw)
      return "typo";
    const lower = raw.toLowerCase().trim();
    if (CATEGORY_MAP[lower])
      return CATEGORY_MAP[lower];
    if (lower.includes("\u6807\u70B9") || lower.includes("punct"))
      return "punctuation";
    if (lower.includes("\u8BED\u6CD5") || lower.includes("gram"))
      return "grammar";
    return "typo";
  }
  buildPrompt(text, mode) {
    const baseInstruction = `\u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u4E2D\u6587\u6821\u5BF9\u52A9\u624B\u3002`;
    let taskInstruction = "";
    let categoryInstruction = "";
    switch (mode) {
      case "quick":
        taskInstruction = `\u8BF7\u8BC6\u522B\u4EE5\u4E0B\u6587\u672C\u4E2D\u7684\u9519\u522B\u5B57\uFF08\u97F3\u8FD1\u5B57\u3001\u5F62\u8FD1\u5B57\u3001\u7B14\u8BEF\uFF09\u3002`;
        categoryInstruction = `category \u56FA\u5B9A\u586B "typo"\u3002`;
        break;
      case "standard":
        taskInstruction = `\u8BF7\u8BC6\u522B\u4EE5\u4E0B\u6587\u672C\u4E2D\u7684\u4EE5\u4E0B\u95EE\u9898\uFF1A
1. \u9519\u522B\u5B57\uFF1A\u97F3\u8FD1\u5B57\u3001\u5F62\u8FD1\u5B57\u3001\u7B14\u8BEF
2. \u6807\u70B9\u7B26\u53F7\u9519\u8BEF\uFF1A\u4E2D\u82F1\u6587\u6807\u70B9\u6DF7\u7528\uFF08\u5982\u4E2D\u6587\u8BED\u5883\u7528\u82F1\u6587\u9017\u53F7\uFF09\u3001\u8FDE\u7EED\u91CD\u590D\u6807\u70B9\uFF08\u5982"\u3002\u3002"\uFF09\u3001\u7F3A\u5931\u6807\u70B9\u3001\u6807\u70B9\u4F4D\u7F6E\u9519\u8BEF
3. \u8BED\u6CD5\u9519\u8BEF\uFF1A\u642D\u914D\u4E0D\u5F53\u3001\u6210\u5206\u6B8B\u7F3A\u3001\u8BED\u5E8F\u4E0D\u5F53\u3001\u91CD\u590D\u8D58\u4F59`;
        categoryInstruction = `category \u6839\u636E\u95EE\u9898\u7C7B\u578B\u586B\u5199\uFF1A"typo"\uFF08\u9519\u522B\u5B57\uFF09\u3001"punctuation"\uFF08\u6807\u70B9\u7B26\u53F7\uFF09\u3001"grammar"\uFF08\u8BED\u6CD5\u9519\u8BEF\uFF09\u3002`;
        break;
      case "deep":
        taskInstruction = `\u8BF7\u8BC6\u522B\u4EE5\u4E0B\u6587\u672C\u4E2D\u7684\u4EE5\u4E0B\u95EE\u9898\uFF1A
1. \u9519\u522B\u5B57\uFF1A\u97F3\u8FD1\u5B57\u3001\u5F62\u8FD1\u5B57\u3001\u7B14\u8BEF
2. \u6807\u70B9\u7B26\u53F7\u9519\u8BEF\uFF1A\u4E2D\u82F1\u6587\u6807\u70B9\u6DF7\u7528\u3001\u8FDE\u7EED\u91CD\u590D\u6807\u70B9\u3001\u7F3A\u5931\u6807\u70B9\u3001\u6807\u70B9\u4F4D\u7F6E\u9519\u8BEF
3. \u8BED\u6CD5\u9519\u8BEF\uFF1A\u642D\u914D\u4E0D\u5F53\u3001\u6210\u5206\u6B8B\u7F3A\u3001\u8BED\u5E8F\u4E0D\u5F53\u3001\u91CD\u590D\u8D58\u4F59
4. \u8868\u8FBE\u4F18\u5316\uFF1A\u53E3\u8BED\u5316\u8868\u8FBE\u5EFA\u8BAE\u66FF\u6362\u4E3A\u4E66\u9762\u8BED\u3001\u76F8\u90BB\u53E5\u5B50\u91CD\u590D\u7528\u8BCD\u5EFA\u8BAE\u66FF\u6362`;
        categoryInstruction = `category \u6839\u636E\u95EE\u9898\u7C7B\u578B\u586B\u5199\uFF1A"typo"\uFF08\u9519\u522B\u5B57\uFF09\u3001"punctuation"\uFF08\u6807\u70B9\u7B26\u53F7\uFF09\u3001"grammar"\uFF08\u8BED\u6CD5\u9519\u8BEF\uFF09\u3002\u8868\u8FBE\u4F18\u5316\u7C7B\u4E5F\u5F52\u5165 "grammar"\u3002`;
        break;
    }
    return `${baseInstruction}
${taskInstruction}

\u6587\u672C\uFF1A
${text}

\u8BF7\u4E25\u683C\u6309\u7167\u4EE5\u4E0B JSON \u6570\u7EC4\u683C\u5F0F\u8FD4\u56DE\u7ED3\u679C\uFF0C\u4E0D\u8981\u8FD4\u56DE\u4EFB\u4F55\u5176\u4ED6\u6587\u5B57\uFF1A
[{"original": "\u516C\u4F5C", "correct": "\u5DE5\u4F5C", "reason": "\u540C\u97F3\u5B57\u8BEF\u7528", "category": "typo"}]

\u6CE8\u610F\uFF1A
1. original \u662F\u539F\u6587\u4E2D\u7684\u9519\u8BEF\u7247\u6BB5\uFF08\u5FC5\u987B\u5B8C\u5168\u5339\u914D\u539F\u6587\uFF09
2. correct \u662F\u5EFA\u8BAE\u7684\u6B63\u786E\u5185\u5BB9
3. reason \u662F\u7B80\u8981\u7684\u7EA0\u9519\u539F\u56E0
4. ${categoryInstruction}
5. \u5982\u679C\u6CA1\u6709\u53D1\u73B0\u95EE\u9898\uFF0C\u8FD4\u56DE\u7A7A\u6570\u7EC4 []
6. \u4FDD\u6301\u539F\u610F\uFF0C\u4E0D\u8981\u6539\u52A8\u6587\u5B66\u6027\u4FEE\u8F9E\u3001\u4E13\u6709\u540D\u8BCD\u3001\u4EBA\u540D\u5730\u540D
7. \u53EA\u8FD4\u56DE\u786E\u5B9A\u6709\u95EE\u9898\u7684\uFF0C\u4E0D\u786E\u5B9A\u7684\u4E0D\u8FD4\u56DE
8. \u53EA\u8FD4\u56DE JSON \u6570\u7EC4\uFF0C\u4E0D\u8981\u6709\u4EFB\u4F55\u5176\u4ED6\u8F93\u51FA`;
  }
  findWordInText(word, text, baseOffset) {
    const results = [];
    if (!word || word.length === 0) {
      return results;
    }
    let startIndex = 0;
    while (true) {
      const index = text.indexOf(word, startIndex);
      if (index === -1)
        break;
      results.push({
        offset: baseOffset + index
      });
      startIndex = index + 1;
    }
    return results;
  }
  async callAPI(prompt) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.settings.timeout);
    try {
      const response = await fetch(this.settings.apiEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.settings.apiKey}`
        },
        body: JSON.stringify({
          model: this.settings.modelName,
          messages: [
            {
              role: "system",
              content: "\u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u4E2D\u6587\u6821\u5BF9\u52A9\u624B\uFF0C\u4E13\u95E8\u8BC6\u522B\u6587\u672C\u4E2D\u7684\u9519\u522B\u5B57\u3001\u6807\u70B9\u9519\u8BEF\u548C\u8BED\u6CD5\u95EE\u9898\u3002\u4F60\u53EA\u8FD4\u56DE JSON \u683C\u5F0F\u7684\u7ED3\u679C\uFF0C\u4E0D\u8FD4\u56DE\u4EFB\u4F55\u5176\u4ED6\u5185\u5BB9\u3002"
            },
            {
              role: "user",
              content: prompt
            }
          ],
          temperature: 0.1,
          max_tokens: 2e3
        }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API \u8BF7\u6C42\u5931\u8D25: ${response.status} - ${errorText}`);
      }
      const data = await response.json();
      if (!data.choices || !data.choices[0] || !data.choices[0].message) {
        throw new Error("API \u8FD4\u56DE\u683C\u5F0F\u9519\u8BEF");
      }
      return data.choices[0].message.content;
    } catch (error) {
      clearTimeout(timeoutId);
      if (error instanceof Error && error.name === "AbortError") {
        throw new Error("API \u8BF7\u6C42\u8D85\u65F6");
      }
      throw error;
    }
  }
  parseResponse(response) {
    try {
      let jsonStr = response.trim();
      const jsonMatch = jsonStr.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        jsonStr = jsonMatch[0];
      }
      const results = JSON.parse(jsonStr);
      if (!Array.isArray(results)) {
        throw new Error("\u8FD4\u56DE\u7ED3\u679C\u4E0D\u662F\u6570\u7EC4");
      }
      const validResults = results.filter(
        (r) => typeof r.original === "string" && typeof r.correct === "string" && r.original.length > 0 && r.correct.length > 0
      );
      return { results: validResults };
    } catch (error) {
      console.error("Failed to parse AI response:", response);
      return { results: [] };
    }
  }
  updateSettings(settings) {
    this.settings = settings;
  }
};

// src/detector/scheduler.ts
var DetectionScheduler = class {
  constructor(settings, app) {
    this.onProgress = null;
    this.settings = settings;
    this.textExtractor = new TextExtractor(app);
    this.textCleaner = new TextCleaner();
    this.textSegmenter = new TextSegmenter(settings.maxSegmentLength);
    this.aiDetector = new AIDetector(settings);
  }
  setProgressCallback(callback) {
    this.onProgress = callback;
  }
  async detect() {
    this.reportProgress({ status: "detecting", currentStep: "\u63D0\u53D6\u6587\u672C..." });
    const extractionResult = this.textExtractor.extractText();
    if (!extractionResult) {
      throw new Error("\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u6587\u6863\u5185\u5BB9");
    }
    const originalText = extractionResult.text;
    const hasSelection = extractionResult.hasSelection;
    const selectionRange = extractionResult.selectionRange;
    this.reportProgress({ status: "detecting", currentStep: "\u6E05\u6D17\u6587\u672C..." });
    const cleanResult = this.textCleaner.clean(originalText);
    const cleanedText = cleanResult.text;
    const mapper = new OffsetMapper(cleanResult.mappings);
    const allResults = [];
    if (this.settings.apiKey) {
      this.reportProgress({ status: "detecting", currentStep: "\u51C6\u5907 AI \u68C0\u6D4B..." });
      const segments = this.textSegmenter.segment(cleanedText);
      if (segments.length > 0) {
        this.reportProgress({
          status: "detecting",
          currentStep: "AI \u5F15\u64CE\u68C0\u6D4B\u4E2D...",
          aiProgress: { current: 0, total: segments.length }
        });
        try {
          const aiResults = await this.aiDetector.detectSegments(segments, (current, total) => {
            this.reportProgress({
              status: "detecting",
              currentStep: "AI \u5F15\u64CE\u68C0\u6D4B\u4E2D...",
              aiProgress: { current, total }
            });
          });
          for (const result of aiResults) {
            if (!this.settings.ignoredWords.includes(result.original)) {
              const originalOffset = mapper.cleanOffsetToOriginal(result.offset);
              allResults.push({
                ...result,
                offset: originalOffset
              });
            }
          }
        } catch (error) {
          console.error("AI detection error:", error);
          new import_obsidian4.Notice("AI \u68C0\u6D4B\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5 API \u914D\u7F6E");
        }
      }
    }
    allResults.sort((a, b) => a.offset - b.offset);
    if (hasSelection && selectionRange) {
      return allResults.filter(
        (r) => r.offset >= selectionRange.from && r.offset < selectionRange.to
      );
    }
    return allResults;
  }
  reportProgress(progress) {
    if (this.onProgress) {
      this.onProgress(progress);
    }
  }
  updateSettings(settings) {
    this.settings = settings;
    this.textSegmenter = new TextSegmenter(settings.maxSegmentLength);
    this.aiDetector.updateSettings(settings);
  }
};

// src/editor/highlight.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var setHighlightsEffect = import_state.StateEffect.define();
var clearHighlightsEffect = import_state.StateEffect.define();
function getCategoryClass(category) {
  switch (category) {
    case "typo":
      return "csc-highlight-typo";
    case "punctuation":
      return "csc-highlight-punctuation";
    case "grammar":
      return "csc-highlight-grammar";
    default:
      return "csc-highlight-typo";
  }
}
function buildDecorationsFromResults(results, docLength) {
  const builder = new import_state.RangeSetBuilder();
  if (results.length === 0) {
    return builder.finish();
  }
  const sortedResults = [...results].sort((a, b) => a.offset - b.offset);
  for (const result of sortedResults) {
    const from = result.offset;
    const to = result.offset + result.original.length;
    if (from >= 0 && to <= docLength && from < to) {
      const decoration = import_view.Decoration.mark({
        class: getCategoryClass(result.category)
      });
      builder.add(from, to, decoration);
    }
  }
  return builder.finish();
}
var highlightsField = import_state.StateField.define({
  create: () => import_view.Decoration.none,
  update: (decorations, tr) => {
    decorations = decorations.map(tr.changes);
    for (const effect of tr.effects) {
      if (effect.is(setHighlightsEffect)) {
        return buildDecorationsFromResults(effect.value, tr.newDoc.length);
      }
      if (effect.is(clearHighlightsEffect)) {
        return import_view.Decoration.none;
      }
    }
    return decorations;
  },
  provide: (f) => import_view.EditorView.decorations.from(f)
});
var highlightTheme = import_view.EditorView.baseTheme({
  ".csc-highlight-typo": {
    backgroundColor: "rgba(230, 57, 70, 0.15)",
    borderBottom: "2px wavy rgba(230, 57, 70, 0.7)"
  },
  ".csc-highlight-punctuation": {
    backgroundColor: "rgba(230, 167, 0, 0.15)",
    borderBottom: "2px wavy rgba(230, 167, 0, 0.7)"
  },
  ".csc-highlight-grammar": {
    backgroundColor: "rgba(86, 156, 214, 0.15)",
    borderBottom: "2px wavy rgba(86, 156, 214, 0.7)"
  }
});
function setHighlights(view, results) {
  view.dispatch({
    effects: setHighlightsEffect.of(results)
  });
}
function clearHighlights(view) {
  view.dispatch({
    effects: clearHighlightsEffect.of(void 0)
  });
}

// src/main.ts
var CSCPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
    this.scheduler = null;
    this.detectionResults = [];
    this.originalText = "";
  }
  async onload() {
    await this.loadSettings();
    await this.syncLicenseStatus();
    this.scheduler = new DetectionScheduler(this.settings, this.app);
    this.registerEditorExtension([highlightsField, highlightTheme]);
    this.registerView(VIEW_TYPE_CSC, (leaf) => {
      this.view = new CSCView(leaf, this);
      return this.view;
    });
    this.addRibbonIcon("spell-check", "\u4E2D\u6587\u6821\u5BF9", () => {
      this.activateView();
    });
    this.addCommand({
      id: "check-chinese-typos",
      name: "\u68C0\u6D4B\u5F53\u524D\u6587\u6863",
      callback: () => {
        this.startDetection();
      }
    });
    this.addCommand({
      id: "clear-highlights",
      name: "\u6E05\u9664\u7F16\u8F91\u5668\u9AD8\u4EAE",
      callback: () => {
        this.clearAllHighlights();
      }
    });
    this.addSettingTab(new CSCSettingTab(this.app, this));
  }
  onunload() {
    if (this.view) {
      this.view = null;
    }
    this.scheduler = null;
    this.clearEditorHighlights();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.scheduler) {
      this.scheduler.updateSettings(this.settings);
    }
  }
  async syncLicenseStatus() {
    const localLicenseType = activationService.checkLocalLicenseStatus();
    if (localLicenseType !== this.settings.licenseType) {
      this.settings.licenseType = localLicenseType;
      await this.saveSettings();
    }
    if (!ActivationService.isFullVersion(localLicenseType)) {
      if (this.settings.detectionMode !== "quick") {
        this.settings.detectionMode = "quick";
        await this.saveSettings();
      }
    }
  }
  isFullVersion() {
    return ActivationService.isFullVersion(this.settings.licenseType);
  }
  canUseMode(mode) {
    if (mode === "quick") {
      return true;
    }
    return this.isFullVersion();
  }
  activateView() {
    var _a;
    const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CSC);
    if (leaf.length > 0) {
      this.app.workspace.revealLeaf(leaf[0]);
      return;
    }
    (_a = this.app.workspace.getRightLeaf(false)) == null ? void 0 : _a.setViewState({
      type: VIEW_TYPE_CSC,
      active: true
    });
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (activeView) {
      return activeView;
    }
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian5.MarkdownView && view.getMode() === "source") {
        return view;
      }
    }
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian5.MarkdownView) {
        return view;
      }
    }
    return null;
  }
  getEditorView() {
    var _a;
    const mdView = this.getMarkdownView();
    if (!mdView)
      return null;
    const cm = (_a = mdView.editor) == null ? void 0 : _a.cm;
    return cm || null;
  }
  async startDetection() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian5.Notice("\u6CA1\u6709\u6253\u5F00\u7684\u6587\u6863");
      return;
    }
    const mdView = this.getMarkdownView();
    if (!mdView) {
      new import_obsidian5.Notice("\u5F53\u524D\u89C6\u56FE\u4E0D\u662F Markdown \u7F16\u8F91\u5668");
      return;
    }
    if (!this.canUseMode(this.settings.detectionMode)) {
      new import_obsidian5.Notice("\u6807\u51C6\u6A21\u5F0F\u548C\u6DF1\u5EA6\u6A21\u5F0F\u9700\u8981\u6B63\u5F0F\u7248");
      return;
    }
    const editor = mdView.editor;
    this.originalText = editor.getValue();
    this.clearEditorHighlights();
    this.activateView();
    if (!this.scheduler) {
      this.scheduler = new DetectionScheduler(this.settings, this.app);
    }
    if (this.view) {
      this.view.setStatus("detecting");
    }
    try {
      this.detectionResults = await this.scheduler.detect();
      if (this.view) {
        this.view.setResults(this.detectionResults, this.originalText);
        this.view.setStatus("completed");
      }
      if (this.detectionResults.length > 0) {
        const editorView = this.getEditorView();
        if (editorView) {
          setHighlights(editorView, this.detectionResults);
        }
      }
      if (this.detectionResults.length === 0) {
        new import_obsidian5.Notice("\u592A\u68D2\u4E86\uFF01\u6CA1\u6709\u53D1\u73B0\u95EE\u9898");
      } else {
        new import_obsidian5.Notice(`\u53D1\u73B0 ${this.detectionResults.length} \u5904\u95EE\u9898`);
      }
    } catch (error) {
      console.error("Detection error:", error);
      if (this.view) {
        this.view.setStatus("error", error instanceof Error ? error.message : "\u68C0\u6D4B\u5931\u8D25");
      }
      new import_obsidian5.Notice("\u68C0\u6D4B\u5931\u8D25: " + (error instanceof Error ? error.message : "\u672A\u77E5\u9519\u8BEF"));
    }
  }
  applyFix(offset, original, replacement) {
    const editor = this.getEditor();
    if (!editor) {
      new import_obsidian5.Notice("\u65E0\u6CD5\u83B7\u53D6\u7F16\u8F91\u5668");
      return false;
    }
    try {
      const from = editor.offsetToPos(offset);
      const to = editor.offsetToPos(offset + original.length);
      const currentText = editor.getRange(from, to);
      if (currentText !== original) {
        console.log(`\u6587\u672C\u4E0D\u5339\u914D: \u671F\u671B "${original}", \u5B9E\u9645 "${currentText}", offset: ${offset}`);
        new import_obsidian5.Notice("\u6587\u672C\u5DF2\u88AB\u4FEE\u6539\u6216\u4F4D\u7F6E\u504F\u79FB\uFF0C\u8BF7\u91CD\u65B0\u68C0\u6D4B");
        return false;
      }
      editor.replaceRange(replacement, from, to);
      this.updateResultsAfterFix(offset, original.length, replacement.length);
      return true;
    } catch (error) {
      console.error("Apply fix error:", error);
      new import_obsidian5.Notice("\u4FEE\u590D\u5931\u8D25");
      return false;
    }
  }
  applyAllFixes() {
    const editor = this.getEditor();
    if (!editor) {
      new import_obsidian5.Notice("\u65E0\u6CD5\u83B7\u53D6\u7F16\u8F91\u5668");
      return 0;
    }
    const sortedResults = [...this.detectionResults].sort((a, b) => b.offset - a.offset);
    let successCount = 0;
    for (const result of sortedResults) {
      if (result.suggestions.length === 0)
        continue;
      const replacement = result.suggestions[0];
      const from = editor.offsetToPos(result.offset);
      const to = editor.offsetToPos(result.offset + result.original.length);
      try {
        const currentText = editor.getRange(from, to);
        if (currentText === result.original) {
          editor.replaceRange(replacement, from, to);
          successCount++;
        }
      } catch (error) {
        console.error("Apply fix error:", error);
      }
    }
    this.detectionResults = [];
    this.originalText = "";
    this.clearEditorHighlights();
    if (this.view) {
      this.view.setResults([]);
    }
    new import_obsidian5.Notice(`\u5DF2\u4FEE\u590D ${successCount} \u5904\u95EE\u9898`);
    return successCount;
  }
  updateResultsAfterFix(fixedOffset, originalLength, replacementLength) {
    const lengthDiff = replacementLength - originalLength;
    this.detectionResults = this.detectionResults.filter(
      (r) => !(r.offset === fixedOffset && r.original.length === originalLength)
    );
    for (const result of this.detectionResults) {
      if (result.offset > fixedOffset) {
        result.offset += lengthDiff;
      }
    }
    if (this.detectionResults.length > 0) {
      const editorView = this.getEditorView();
      if (editorView) {
        setHighlights(editorView, this.detectionResults);
      }
    } else {
      this.clearEditorHighlights();
    }
    if (this.view) {
      this.view.setResults(this.detectionResults);
    }
  }
  clearEditorHighlights() {
    const editorView = this.getEditorView();
    if (editorView) {
      clearHighlights(editorView);
    }
  }
  clearAllHighlights() {
    this.clearEditorHighlights();
    this.detectionResults = [];
    if (this.view) {
      this.view.setResults([]);
    }
    new import_obsidian5.Notice("\u5DF2\u6E05\u9664\u7F16\u8F91\u5668\u9AD8\u4EAE");
  }
  getEditor() {
    const mdView = this.getMarkdownView();
    return (mdView == null ? void 0 : mdView.editor) || null;
  }
  getResults() {
    return this.detectionResults;
  }
  getOriginalText() {
    return this.originalText;
  }
};
